package com.rain.urs.dao.model;
// Generated Mar 4, 2016 11:51:43 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import javax.xml.bind.annotation.XmlRootElement;



/**
 * Address generated by hbm2java
 */


public class Address  implements java.io.Serializable {


     @Override
	public String toString() {
		return "Address [idAddress=" + idAddress + ", officename=" + officename + ", pincode=" + pincode
				+ ", officetype=" + officetype + ", deliverystatus=" + deliverystatus + ", divisionname=" + divisionname
				+ ", regionname=" + regionname + ", circlename=" + circlename + ", taluk=" + taluk + ", districtname="
				+ districtname + ", statename=" + statename + ", telephone=" + telephone + ", relatedSuboffice="
				+ relatedSuboffice + ", relatedHeadoffice=" + relatedHeadoffice + ", longitude=" + longitude
				+ ", latitude=" + latitude + "]";
	}

	private Long idAddress;
     private String officename;
     private String pincode;
     private String officetype;
     private String deliverystatus;
     private String divisionname;
     private String regionname;
     private String circlename;
     private String taluk;
     private String districtname;
     private String statename;
     private String telephone;
     private String relatedSuboffice;
     private String relatedHeadoffice;
     private String longitude;
     private String latitude;
   //  private Set personalAddresses = new HashSet(0);

    public Address() {
    }

    public Address(String officename, String pincode, String officetype, String deliverystatus, String divisionname, String regionname, String circlename, String taluk, String districtname, String statename, String telephone, String relatedSuboffice, String relatedHeadoffice, String longitude, String latitude) {
       this.officename = officename;
       this.pincode = pincode;
       this.officetype = officetype;
       this.deliverystatus = deliverystatus;
       this.divisionname = divisionname;
       this.regionname = regionname;
       this.circlename = circlename;
       this.taluk = taluk;
       this.districtname = districtname;
       this.statename = statename;
       this.telephone = telephone;
       this.relatedSuboffice = relatedSuboffice;
       this.relatedHeadoffice = relatedHeadoffice;
       this.longitude = longitude;
       this.latitude = latitude;
 //      this.personalAddresses = personalAddresses;
    }
   
    public Long getIdAddress() {
        return this.idAddress;
    }
    
    public void setIdAddress(Long idAddress) {
        this.idAddress = idAddress;
    }
    public String getOfficename() {
        return this.officename;
    }
    
    public void setOfficename(String officename) {
        this.officename = officename;
    }
    public String getPincode() {
        return this.pincode;
    }
    
    public void setPincode(String pincode) {
        this.pincode = pincode;
    }
    public String getOfficetype() {
        return this.officetype;
    }
    
    public void setOfficetype(String officetype) {
        this.officetype = officetype;
    }
    public String getDeliverystatus() {
        return this.deliverystatus;
    }
    
    public void setDeliverystatus(String deliverystatus) {
        this.deliverystatus = deliverystatus;
    }
    public String getDivisionname() {
        return this.divisionname;
    }
    
    public void setDivisionname(String divisionname) {
        this.divisionname = divisionname;
    }
    public String getRegionname() {
        return this.regionname;
    }
    
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }
    public String getCirclename() {
        return this.circlename;
    }
    
    public void setCirclename(String circlename) {
        this.circlename = circlename;
    }
    public String getTaluk() {
        return this.taluk;
    }
    
    public void setTaluk(String taluk) {
        this.taluk = taluk;
    }
    public String getDistrictname() {
        return this.districtname;
    }
    
    public void setDistrictname(String districtname) {
        this.districtname = districtname;
    }
    public String getStatename() {
        return this.statename;
    }
    
    public void setStatename(String statename) {
        this.statename = statename;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getRelatedSuboffice() {
        return this.relatedSuboffice;
    }
    
    public void setRelatedSuboffice(String relatedSuboffice) {
        this.relatedSuboffice = relatedSuboffice;
    }
    public String getRelatedHeadoffice() {
        return this.relatedHeadoffice;
    }
    
    public void setRelatedHeadoffice(String relatedHeadoffice) {
        this.relatedHeadoffice = relatedHeadoffice;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
//    public Set getPersonalAddresses() {
//        return this.personalAddresses;
//    }
//    
//    public void setPersonalAddresses(Set personalAddresses) {
//        this.personalAddresses = personalAddresses;
//    }

}
