package com.rain.urs.dao.model;
// Generated Mar 4, 2016 11:51:43 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PersonalInfo generated by hbm2java
 */
public class PersonalInfo  implements java.io.Serializable {


     private Integer idPersonalInfo;
     private String firstName;
     private String lastName;
     private String email;
     private String mobileNumber;
     private Set personalAddresses = new HashSet(0);

    public PersonalInfo() {
    }

    public PersonalInfo(String firstName, String lastName, String email, String mobileNumber, Set personalAddresses) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.mobileNumber = mobileNumber;
       this.personalAddresses = personalAddresses;
    }
   
    public Integer getIdPersonalInfo() {
        return this.idPersonalInfo;
    }
    
    public void setIdPersonalInfo(Integer idPersonalInfo) {
        this.idPersonalInfo = idPersonalInfo;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobileNumber() {
        return this.mobileNumber;
    }
    
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }
    public Set getPersonalAddresses() {
        return this.personalAddresses;
    }
    
    public void setPersonalAddresses(Set personalAddresses) {
        this.personalAddresses = personalAddresses;
    }




}


