package com.rain.urs.dao.model;
// Generated Mar 4, 2016 11:51:43 PM by Hibernate Tools 3.2.1.GA



/**
 * PersonalAddress generated by hbm2java
 */
public class PersonalAddress  implements java.io.Serializable {


     private Integer idPersonalAddress;
     private Address address;
     private PersonalInfo personalInfo;

    public PersonalAddress() {
    }

    public PersonalAddress(Address address, PersonalInfo personalInfo) {
       this.address = address;
       this.personalInfo = personalInfo;
    }
   
    public Integer getIdPersonalAddress() {
        return this.idPersonalAddress;
    }
    
    public void setIdPersonalAddress(Integer idPersonalAddress) {
        this.idPersonalAddress = idPersonalAddress;
    }
    public Address getAddress() {
        return this.address;
    }
    
    public void setAddress(Address address) {
        this.address = address;
    }
    public PersonalInfo getPersonalInfo() {
        return this.personalInfo;
    }
    
    public void setPersonalInfo(PersonalInfo personalInfo) {
        this.personalInfo = personalInfo;
    }




}


