-- MySQL Script generated by MySQL Workbench
-- 07/31/17 22:33:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema saas_core_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saas_core_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saas_core_db` DEFAULT CHARACTER SET utf8 ;
USE `saas_core_db` ;

-- -----------------------------------------------------
-- Table `saas_core_db`.`atndnc_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`atndnc_type` (
  `ATNDNC_TYPE_ID` BIGINT(8) NOT NULL,
  `TYP_NME` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  PRIMARY KEY (`ATNDNC_TYPE_ID`),
  UNIQUE INDEX `TYP_NME_UNIQUE` (`TYP_NME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`dvsn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`dvsn` (
  `DVSN_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `DVSN_NME` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DVSN_ID`),
  UNIQUE INDEX `DVSN_NME_UNIQUE` (`DVSN_NME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`grd_lvl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`grd_lvl` (
  `GRD_LVL_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `GRD_NME` VARCHAR(8) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GRD_LVL_ID`),
  UNIQUE INDEX `GRD_NME_UNIQUE` (`GRD_NME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`schl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`schl` (
  `SCHL_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `SCHL_CDE_NME` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `ACTV_IND` INT(1) NOT NULL,
  PRIMARY KEY (`SCHL_ID`),
  UNIQUE INDEX `SCHL_CDE_NME_UNIQUE` (`SCHL_CDE_NME` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`schl_grd_lvl_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`schl_grd_lvl_map` (
  `SCHL_ID` BIGINT(8) NOT NULL,
  `GRD_LVL_ID` BIGINT(8) NOT NULL,
  `SCHL_GRD_LVL_MAP_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SCHL_GRD_LVL_MAP_ID`),
  INDEX `fk_SCHL_GRD_LVL_MAP_GRD_LVL` (`GRD_LVL_ID` ASC),
  INDEX `fk_SCHL_GRD_LVL_MAP_SCHL` (`SCHL_ID` ASC),
  CONSTRAINT `fk_SCHL_has_GRD_LVL_GRD_LVL1`
    FOREIGN KEY (`GRD_LVL_ID`)
    REFERENCES `saas_core_db`.`grd_lvl` (`GRD_LVL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SCHL_has_GRD_LVL_SCHL1`
    FOREIGN KEY (`SCHL_ID`)
    REFERENCES `saas_core_db`.`schl` (`SCHL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`dvsn_schl_grd_lvl_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`dvsn_schl_grd_lvl_map` (
  `DVSN_SCHL_GRD_LVL_MAP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `DVSN_ID` BIGINT(8) NOT NULL,
  `SCHL_GRD_LVL_MAP_ID` BIGINT(8) NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`DVSN_SCHL_GRD_LVL_MAP_ID`),
  INDEX `fk_DVSN_SCHL_GRD_LVL_MAP_dvsn1_idx` (`DVSN_ID` ASC),
  INDEX `fk_DVSN_SCHL_GRD_LVL_MAP_schl_grd_lvl_map1_idx` (`SCHL_GRD_LVL_MAP_ID` ASC),
  CONSTRAINT `fk_DVSN_SCHL_GRD_LVL_MAP_dvsn1`
    FOREIGN KEY (`DVSN_ID`)
    REFERENCES `saas_core_db`.`dvsn` (`DVSN_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DVSN_SCHL_GRD_LVL_MAP_schl_grd_lvl_map1`
    FOREIGN KEY (`SCHL_GRD_LVL_MAP_ID`)
    REFERENCES `saas_core_db`.`schl_grd_lvl_map` (`SCHL_GRD_LVL_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`emg_ctct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`emg_ctct` (
  `EMG_CTCT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `LST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `ACT_IND` INT(1) NULL DEFAULT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`EMG_CTCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`stdnt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`stdnt` (
  `STDNT_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `FST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `LST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `EMG_CTCT_ID` INT(11) NOT NULL,
  `GNDR` VARCHAR(8) NOT NULL,
  `DVSN_SCHL_GRD_LVL_MAP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`STDNT_ID`),
  INDEX `fk_stdnt_EMG_CTCT1_idx` (`EMG_CTCT_ID` ASC),
  INDEX `fk_stdnt_DVSN_SCHL_GRD_LVL_MAP1_idx` (`DVSN_SCHL_GRD_LVL_MAP_ID` ASC),
  CONSTRAINT `fk_stdnt_DVSN_SCHL_GRD_LVL_MAP1`
    FOREIGN KEY (`DVSN_SCHL_GRD_LVL_MAP_ID`)
    REFERENCES `saas_core_db`.`dvsn_schl_grd_lvl_map` (`DVSN_SCHL_GRD_LVL_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stdnt_EMG_CTCT1`
    FOREIGN KEY (`EMG_CTCT_ID`)
    REFERENCES `saas_core_db`.`emg_ctct` (`EMG_CTCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`atndnc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`atndnc` (
  `ATNDNC` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `STDNT_ID` BIGINT(8) NOT NULL,
  `ATNDNC_TYPE_ID` BIGINT(8) NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`ATNDNC`),
  INDEX `fk_ATNDNC_STDNT1_idx` (`STDNT_ID` ASC),
  INDEX `fk_ATNDNC_ATNDNC_TYPE1_idx` (`ATNDNC_TYPE_ID` ASC),
  CONSTRAINT `fk_ATNDNC_ATNDNC_TYPE1`
    FOREIGN KEY (`ATNDNC_TYPE_ID`)
    REFERENCES `saas_core_db`.`atndnc_type` (`ATNDNC_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ATNDNC_STDNT1`
    FOREIGN KEY (`STDNT_ID`)
    REFERENCES `saas_core_db`.`stdnt` (`STDNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`clstr_dat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`clstr_dat` (
  `CLSTR_DAT_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `HOST` VARCHAR(45) NOT NULL,
  `HTTP_PORT` VARCHAR(45) NULL DEFAULT NULL,
  `HTTPS_PORT` VARCHAR(45) NULL DEFAULT NULL,
  `AKKA_PORT` VARCHAR(45) NULL DEFAULT NULL,
  `TCP_PORT` VARCHAR(45) NULL DEFAULT NULL,
  `APP_NME` VARCHAR(45) NULL DEFAULT NULL,
  `DMN_NME` VARCHAR(45) NULL DEFAULT NULL,
  `SRVR_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CLSTR_DAT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sbjct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sbjct` (
  `SBJCT_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `SBJCT_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SBJCT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`schl_sbjct_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`schl_sbjct_map` (
  `SCHL_SBJCT_MAP_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `SCHL_ID` BIGINT(8) NOT NULL,
  `SBJCT_ID` BIGINT(8) NOT NULL,
  `TYPE` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`SCHL_SBJCT_MAP_ID`),
  INDEX `fk_SCHL_SBJCT_MAP_schl1_idx` (`SCHL_ID` ASC),
  INDEX `fk_SCHL_SBJCT_MAP_sbjct1_idx` (`SBJCT_ID` ASC),
  CONSTRAINT `fk_SCHL_SBJCT_MAP_sbjct1`
    FOREIGN KEY (`SBJCT_ID`)
    REFERENCES `saas_core_db`.`sbjct` (`SBJCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SCHL_SBJCT_MAP_schl1`
    FOREIGN KEY (`SCHL_ID`)
    REFERENCES `saas_core_db`.`schl` (`SCHL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`schl_usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`schl_usr` (
  `SCHL_USR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_NBR` VARCHAR(20) NULL DEFAULT NULL,
  `CRTD_BY_USSR` VARCHAR(15) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NULL DEFAULT NULL,
  `UPTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `UPTD_DTTM` DATETIME NULL DEFAULT NULL,
  `SCHL_ID` BIGINT(8) NOT NULL,
  PRIMARY KEY (`SCHL_USR_ID`),
  INDEX `fk_schl_usr_schl1_idx` (`SCHL_ID` ASC),
  CONSTRAINT `fk_schl_usr_schl1`
    FOREIGN KEY (`SCHL_ID`)
    REFERENCES `saas_core_db`.`schl` (`SCHL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`tchr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`tchr` (
  `TCHR_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `RESP_PRI` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `SCHL_USR_ID` INT(11) NOT NULL,
  `DVSN_SCHL_GRD_LVL_MAP_ID` INT(11) NOT NULL,
  PRIMARY KEY (`TCHR_ID`),
  INDEX `fk_tchr_schl_usr1_idx` (`SCHL_USR_ID` ASC),
  INDEX `fk_tchr_DVSN_SCHL_GRD_LVL_MAP1_idx` (`DVSN_SCHL_GRD_LVL_MAP_ID` ASC),
  CONSTRAINT `fk_tchr_DVSN_SCHL_GRD_LVL_MAP1`
    FOREIGN KEY (`DVSN_SCHL_GRD_LVL_MAP_ID`)
    REFERENCES `saas_core_db`.`dvsn_schl_grd_lvl_map` (`DVSN_SCHL_GRD_LVL_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tchr_schl_usr1`
    FOREIGN KEY (`SCHL_USR_ID`)
    REFERENCES `saas_core_db`.`schl_usr` (`SCHL_USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sbjct_tchr_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sbjct_tchr_map` (
  `SBJCT_TCHR_MAP_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `TCHR_ID` BIGINT(8) NOT NULL,
  `SCHL_SBJCT_MAP_ID` BIGINT(8) NOT NULL,
  PRIMARY KEY (`SBJCT_TCHR_MAP_ID`),
  INDEX `fk_sbjct_tchr_map_tchr1_idx` (`TCHR_ID` ASC),
  INDEX `fk_sbjct_tchr_map_SCHL_SBJCT_MAP1_idx` (`SCHL_SBJCT_MAP_ID` ASC),
  CONSTRAINT `fk_sbjct_tchr_map_SCHL_SBJCT_MAP1`
    FOREIGN KEY (`SCHL_SBJCT_MAP_ID`)
    REFERENCES `saas_core_db`.`schl_sbjct_map` (`SCHL_SBJCT_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sbjct_tchr_map_tchr1`
    FOREIGN KEY (`TCHR_ID`)
    REFERENCES `saas_core_db`.`tchr` (`TCHR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`dvsn_tchr_sujct_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`dvsn_tchr_sujct_map` (
  `DVSN_TCHR_SUJCT_MAP_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `SBJCT_TCHR_MAP_ID` BIGINT(8) NOT NULL,
  `DVSN_SCHL_GRD_LVL_MAP_ID` INT(11) NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`DVSN_TCHR_SUJCT_MAP_ID`),
  INDEX `fk_DVSN_TCHR_SUJCT_MAP_sbjct_tchr_map1_idx` (`SBJCT_TCHR_MAP_ID` ASC),
  INDEX `fk_DVSN_TCHR_SUJCT_MAP_DVSN_SCHL_GRD_LVL_MAP1_idx` (`DVSN_SCHL_GRD_LVL_MAP_ID` ASC),
  CONSTRAINT `fk_DVSN_TCHR_SUJCT_MAP_DVSN_SCHL_GRD_LVL_MAP1`
    FOREIGN KEY (`DVSN_SCHL_GRD_LVL_MAP_ID`)
    REFERENCES `saas_core_db`.`dvsn_schl_grd_lvl_map` (`DVSN_SCHL_GRD_LVL_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DVSN_TCHR_SUJCT_MAP_sbjct_tchr_map1`
    FOREIGN KEY (`SBJCT_TCHR_MAP_ID`)
    REFERENCES `saas_core_db`.`sbjct_tchr_map` (`SBJCT_TCHR_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`exm_grp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`exm_grp` (
  `EXM_GRP_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `GRP_CDE_NME` VARCHAR(16) NULL DEFAULT NULL,
  `YEAR` VARCHAR(8) NULL DEFAULT NULL,
  `EXM_GRP_DESC` VARCHAR(256) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `TYPE_NME` VARCHAR(16) NULL,
  `SCHL_ID` BIGINT(8) NOT NULL,
  PRIMARY KEY (`EXM_GRP_ID`),
  UNIQUE INDEX `CDE_NME_UNIQUE` (`GRP_CDE_NME` ASC),
  INDEX `fk_exm_grp_schl1_idx` (`SCHL_ID` ASC),
  CONSTRAINT `fk_exm_grp_schl1`
    FOREIGN KEY (`SCHL_ID`)
    REFERENCES `saas_core_db`.`schl` (`SCHL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`exm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`exm` (
  `EXM_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `EXM_GRP_ID` BIGINT(8) NOT NULL,
  `MXM_MRK` VARCHAR(45) NULL DEFAULT NULL,
  `EXM_CDE_NME` VARCHAR(45) NULL DEFAULT NULL,
  `DTE_OF_EXM` DATE NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `SCHL_SBJCT_MAP_ID` BIGINT(8) NOT NULL,
  PRIMARY KEY (`EXM_ID`),
  INDEX `fk_EXM_EXAM_GRP_idx` (`EXM_GRP_ID` ASC),
  INDEX `fk_exm_SCHL_SBJCT_MAP1_idx` (`SCHL_SBJCT_MAP_ID` ASC),
  CONSTRAINT `fk_EXM_EXAM_GRP`
    FOREIGN KEY (`EXM_GRP_ID`)
    REFERENCES `saas_core_db`.`exm_grp` (`EXM_GRP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exm_SCHL_SBJCT_MAP1`
    FOREIGN KEY (`SCHL_SBJCT_MAP_ID`)
    REFERENCES `saas_core_db`.`schl_sbjct_map` (`SCHL_SBJCT_MAP_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`mrk_lst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`mrk_lst` (
  `MRK_LST_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `EXM_ID` BIGINT(8) NOT NULL,
  `STDNT_ID` BIGINT(8) NOT NULL,
  `MRK` VARCHAR(8) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) CHARACTER SET 'big5' NOT NULL,
  `MAX_MRK` VARCHAR(45) NULL,
  PRIMARY KEY (`MRK_LST_ID`),
  INDEX `fk_MRK_LST_EXM1_idx` (`EXM_ID` ASC),
  INDEX `fk_MRK_LST_STDNT1_idx` (`STDNT_ID` ASC),
  CONSTRAINT `fk_MRK_LST_EXM1`
    FOREIGN KEY (`EXM_ID`)
    REFERENCES `saas_core_db`.`exm` (`EXM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MRK_LST_STDNT1`
    FOREIGN KEY (`STDNT_ID`)
    REFERENCES `saas_core_db`.`stdnt` (`STDNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`ntfn_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`ntfn_type` (
  `NTFN_TYPE_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `TYPE_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`NTFN_TYPE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`ntfn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`ntfn` (
  `NTFN_ID` BIGINT(8) NOT NULL,
  `STDNT_ID` BIGINT(8) NOT NULL,
  `NTFN_TYPE_ID` BIGINT(8) NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`NTFN_ID`),
  INDEX `fk_NTFCN_stdnt1_idx` (`STDNT_ID` ASC),
  INDEX `fk_NTFN_NTFN_TYPE1_idx` (`NTFN_TYPE_ID` ASC),
  CONSTRAINT `fk_NTFCN_stdnt1`
    FOREIGN KEY (`STDNT_ID`)
    REFERENCES `saas_core_db`.`stdnt` (`STDNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NTFN_NTFN_TYPE1`
    FOREIGN KEY (`NTFN_TYPE_ID`)
    REFERENCES `saas_core_db`.`ntfn_type` (`NTFN_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`prnt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`prnt` (
  `PRNT_ID` BIGINT(8) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `PRNT_PRI` INT(1) NULL DEFAULT NULL,
  `ACTV_IND` INT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PRNT_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`prnt_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`prnt_auth` (
  `PRNT_AUTH_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `LGN_NME` VARCHAR(45) NULL DEFAULT NULL,
  `PSWD` VARCHAR(45) NULL DEFAULT NULL,
  `PRNT_ID` BIGINT(8) NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`PRNT_AUTH_ID`),
  UNIQUE INDEX `LGN_NME_UNIQUE` (`LGN_NME` ASC),
  INDEX `fk_PRNT_AUTH_PRNT1_idx` (`PRNT_ID` ASC),
  CONSTRAINT `fk_PRNT_AUTH_PRNT1`
    FOREIGN KEY (`PRNT_ID`)
    REFERENCES `saas_core_db`.`prnt` (`PRNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`prnt_cntct_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`prnt_cntct_det` (
  `PRNT_CNTCT_DET_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `FST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `LST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `PRNT_ID` BIGINT(8) NOT NULL,
  `PRNT_CTCT_TYPE` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NULL DEFAULT NULL,
  `PHN_NUM` VARCHAR(45) NULL DEFAULT NULL,
  `MOB_NUM` VARCHAR(45) NULL DEFAULT NULL,
  `ADDRESS` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`PRNT_CNTCT_DET_ID`),
  INDEX `fk_PRNT_CTCT_DET_PRNT` (`PRNT_ID` ASC),
  CONSTRAINT `fk_PRNT_CTCT_DET_PRNT1`
    FOREIGN KEY (`PRNT_ID`)
    REFERENCES `saas_core_db`.`prnt` (`PRNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`prnt_devc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`prnt_devc` (
  `PRNT_DEVC_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `DEVC_TYPE` VARCHAR(45) NULL DEFAULT NULL,
  `REG_COD` VARCHAR(45) NULL DEFAULT NULL,
  `PRNT_ID` BIGINT(8) NOT NULL,
  `NTFN_PREF` VARCHAR(8) NULL DEFAULT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`PRNT_DEVC_ID`),
  INDEX `fk_PRNT_DEVC_prnt1_idx` (`PRNT_ID` ASC),
  CONSTRAINT `fk_PRNT_DEVC_prnt1`
    FOREIGN KEY (`PRNT_ID`)
    REFERENCES `saas_core_db`.`prnt` (`PRNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`prnt_logn_atmt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`prnt_logn_atmt` (
  `PRNT_USR_LOGN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `LOGIN_STATUS` CHAR(1) NULL DEFAULT NULL,
  `CRTD_USR` VARCHAR(15) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(15) CHARACTER SET 'big5' NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `PRNT_ID` BIGINT(8) NOT NULL,
  PRIMARY KEY (`PRNT_USR_LOGN_ID`),
  UNIQUE INDEX `idSYS_USR_LOGN_ID_UNIQUE` (`PRNT_USR_LOGN_ID` ASC),
  INDEX `fk_prnt_logn_atmt_prnt1_idx` (`PRNT_ID` ASC),
  CONSTRAINT `fk_prnt_logn_atmt_prnt1`
    FOREIGN KEY (`PRNT_ID`)
    REFERENCES `saas_core_db`.`prnt` (`PRNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`schl_ctct_det`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`schl_ctct_det` (
  `SCHL_CTCT_DET_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `SCHL_NME` VARCHAR(45) NULL DEFAULT NULL,
  `ADDR` VARCHAR(45) NULL DEFAULT NULL,
  `CITY` VARCHAR(45) NULL DEFAULT NULL,
  `DISTRICT` VARCHAR(45) NULL DEFAULT NULL,
  `STATE` VARCHAR(45) NULL DEFAULT NULL,
  `PIN` VARCHAR(45) NULL DEFAULT NULL,
  `POST` VARCHAR(45) NULL DEFAULT NULL,
  `SCHL_ID` BIGINT(8) NOT NULL,
  `ADDR_TYPE` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SCHL_CTCT_DET_ID`),
  INDEX `fk_SCHL_CTCT_DET_SCHL1_idx` (`SCHL_ID` ASC),
  CONSTRAINT `fk_SCHL_CTCT_DET_SCHL1`
    FOREIGN KEY (`SCHL_ID`)
    REFERENCES `saas_core_db`.`schl` (`SCHL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`schl_usr_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`schl_usr_role` (
  `SYS_USR_ROLE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_USR` VARCHAR(15) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(15) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  PRIMARY KEY (`SYS_USR_ROLE_ID`),
  UNIQUE INDEX `SYS_USR_ROLE_ID_UNIQUE` (`SYS_USR_ROLE_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`stdnt_prnt_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`stdnt_prnt_map` (
  `STDNT_ID` BIGINT(8) NOT NULL,
  `PRNT_ID` BIGINT(8) NOT NULL,
  `STDNT_PRNT_MAP_ID` BIGINT(8) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `CRTD_USR` VARCHAR(45) NOT NULL,
  `LST_UPTD_DTTM` DATETIME NOT NULL,
  `LST_UPTD_USR` VARCHAR(45) NOT NULL,
  `ACT_IND` INT(1) NOT NULL,
  PRIMARY KEY (`STDNT_PRNT_MAP_ID`),
  INDEX `fk_STDNT_has_PRNT_PRNT1_idx` (`PRNT_ID` ASC),
  INDEX `fk_STDNT_has_PRNT_STDNT1_idx` (`STDNT_ID` ASC),
  CONSTRAINT `fk_STDNT_has_PRNT_PRNT1`
    FOREIGN KEY (`PRNT_ID`)
    REFERENCES `saas_core_db`.`prnt` (`PRNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STDNT_has_PRNT_STDNT1`
    FOREIGN KEY (`STDNT_ID`)
    REFERENCES `saas_core_db`.`stdnt` (`STDNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sys_usr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sys_usr` (
  `SYS_USR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ID_NBR` VARCHAR(20) NULL DEFAULT NULL,
  `CRTD_BY_USSR` VARCHAR(15) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NULL DEFAULT NULL,
  `UPTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `UPTD_DTTM` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`SYS_USR_ID`),
  UNIQUE INDEX `SYS_USR_ID_UNIQUE` (`SYS_USR_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sys_usr_logn`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sys_usr_logn` (
  `SYS_USR_LOGN_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USR_NME` VARCHAR(45) NOT NULL,
  `USR_PWD` VARCHAR(45) NULL DEFAULT NULL,
  `USR_STAT` ENUM('ACTIVE', 'NOT_ACTIVE') NOT NULL,
  `CRTD_BY_USR` VARCHAR(15) NOT NULL,
  `CRTD_DTTM` DATETIME NOT NULL,
  `UPTD_BY_USR` VARCHAR(15) NOT NULL,
  `UPTD_DTTM` DATETIME NOT NULL,
  `SYS_USR_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SYS_USR_LOGN_ID`),
  UNIQUE INDEX `SYS_USR_LOGN_ID_UNIQUE` (`SYS_USR_LOGN_ID` ASC),
  INDEX `fk_SYS_USR_LOGN_SYS_USR1_idx1` (`SYS_USR_ID` ASC),
  CONSTRAINT `fk_SYS_USR_LOGN_SYS_USR1`
    FOREIGN KEY (`SYS_USR_ID`)
    REFERENCES `saas_core_db`.`sys_usr` (`SYS_USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sys_usr_logn_atmt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sys_usr_logn_atmt` (
  `SYS_USR_LOGN_ID` INT(11) NOT NULL,
  `USR_LOGIN_STATUS` CHAR(1) NULL DEFAULT NULL,
  `CRTD_BY_USSR` VARCHAR(15) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NULL DEFAULT NULL,
  `UPTD_BY_USR` VARCHAR(15) CHARACTER SET 'big5' NULL DEFAULT NULL,
  `UPTD_DTTM` DATETIME NULL DEFAULT NULL,
  `SYS_USR_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SYS_USR_LOGN_ID`),
  UNIQUE INDEX `idSYS_USR_LOGN_ID_UNIQUE` (`SYS_USR_LOGN_ID` ASC),
  INDEX `fk_SYS_USR_LOGN_ATMT_SYS_USR1_idx` (`SYS_USR_ID` ASC),
  CONSTRAINT `fk_SYS_USR_LOGN_ATMT_SYS_USR1`
    FOREIGN KEY (`SYS_USR_ID`)
    REFERENCES `saas_core_db`.`sys_usr` (`SYS_USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sys_usr_prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sys_usr_prof` (
  `SYS_USR_PROF_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USR_EML` VARCHAR(45) NOT NULL,
  `USR_PHN` VARCHAR(45) NOT NULL,
  `FST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `LST_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NULL DEFAULT NULL,
  `UPTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `UPTD_DTTM` DATETIME NULL DEFAULT NULL,
  `SYS_USR_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SYS_USR_PROF_ID`),
  UNIQUE INDEX `SYS_USR_PROF_ID_UNIQUE` (`SYS_USR_PROF_ID` ASC),
  INDEX `fk_SYS_USR_PROF_SYS_USR_idx` (`SYS_USR_ID` ASC),
  CONSTRAINT `fk_SYS_USR_PROF_SYS_USR`
    FOREIGN KEY (`SYS_USR_ID`)
    REFERENCES `saas_core_db`.`sys_usr` (`SYS_USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sys_usr_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sys_usr_role` (
  `SYS_USR_ROLE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NME` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NULL DEFAULT NULL,
  `UPTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `UPTD_DTTM` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`SYS_USR_ROLE_ID`),
  UNIQUE INDEX `SYS_USR_ROLE_ID_UNIQUE` (`SYS_USR_ROLE_ID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`sys_usr_role_map`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`sys_usr_role_map` (
  `SYS_USR_ROLE_MAP_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ROLE_STATUS` VARCHAR(45) NULL DEFAULT NULL,
  `CRTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `CRTD_DTTM` DATETIME NULL DEFAULT NULL,
  `UPTD_BY_USR` VARCHAR(15) NULL DEFAULT NULL,
  `UPTD_DTT` DATETIME NULL DEFAULT NULL,
  `SYS_USR_ID` INT(11) NOT NULL,
  `SYS_USR_ROLE_NME` VARCHAR(45) NULL DEFAULT NULL,
  `SYS_USR_ROLE_ID` INT(11) NOT NULL,
  PRIMARY KEY (`SYS_USR_ROLE_MAP_ID`),
  UNIQUE INDEX `SYS_USR_ROLE_MAP_ID_UNIQUE` (`SYS_USR_ROLE_MAP_ID` ASC),
  INDEX `fk_SYS_USR_ROLE_MAP_SYS_USR1_idx` (`SYS_USR_ID` ASC),
  INDEX `fk_SYS_USR_ROLE_MAP_SYS_USR_ROLE1_idx` (`SYS_USR_ROLE_ID` ASC),
  CONSTRAINT `fk_SYS_USR_ROLE_MAP_SYS_USR1`
    FOREIGN KEY (`SYS_USR_ID`)
    REFERENCES `saas_core_db`.`sys_usr` (`SYS_USR_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SYS_USR_ROLE_MAP_SYS_USR_ROLE1`
    FOREIGN KEY (`SYS_USR_ROLE_ID`)
    REFERENCES `saas_core_db`.`sys_usr_role` (`SYS_USR_ROLE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `saas_core_db`.`CFTRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saas_core_db`.`CFTRA` (
  `CFTRA_ID` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `NME` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `PHN_NUM` VARCHAR(45) NULL,
  `MOB_NUM` VARCHAR(45) NULL,
  `SCHL_ID` BIGINT(8) NOT NULL,
  PRIMARY KEY (`CFTRA_ID`),
  INDEX `fk_CFTRA_schl1_idx` (`SCHL_ID` ASC),
  CONSTRAINT `fk_CFTRA_schl1`
    FOREIGN KEY (`SCHL_ID`)
    REFERENCES `saas_core_db`.`schl` (`SCHL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
