package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AtndncType generated by hbm2java
 */
@Entity
@Table(name = "atndnc_type", catalog = "saas_core_db", uniqueConstraints = @UniqueConstraint(columnNames = "TYP_NME"))
public class AtndncType extends AbstractAuditEntity {

	private long atndncTypeId;
	private String typNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<Atndnc> atndncs = new HashSet<Atndnc>(0);

	public AtndncType() {
	}

	public AtndncType(long atndncTypeId, String typNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr) {
		this.atndncTypeId = atndncTypeId;
		this.typNme = typNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public AtndncType(long atndncTypeId, String typNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr, Set<Atndnc> atndncs) {
		this.atndncTypeId = atndncTypeId;
		this.typNme = typNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.atndncs = atndncs;
	}

	@Id

	@Column(name = "ATNDNC_TYPE_ID", unique = true, nullable = false)
	public long getAtndncTypeId() {
		return this.atndncTypeId;
	}

	public void setAtndncTypeId(long atndncTypeId) {
		this.atndncTypeId = atndncTypeId;
	}

	@Column(name = "TYP_NME", unique = true, nullable = false, length = 45)
	public String getTypNme() {
		return this.typNme;
	}

	public void setTypNme(String typNme) {
		this.typNme = typNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atndncType")
	public Set<Atndnc> getAtndncs() {
		return this.atndncs;
	}

	public void setAtndncs(Set<Atndnc> atndncs) {
		this.atndncs = atndncs;
	}

}
