package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cftra generated by hbm2java
 */
@Entity
@Table(name = "cftra", catalog = "saas_core_db")
public class Cftra extends AbstractAuditEntity {

	private Long cftraId;
	private Schl schl;
	private String nme;
	private String email;
	private String phnNum;
	private String mobNum;

	public Cftra() {
	}

	public Cftra(Schl schl) {
		this.schl = schl;
	}

	public Cftra(Schl schl, String nme, String email, String phnNum, String mobNum) {
		this.schl = schl;
		this.nme = nme;
		this.email = email;
		this.phnNum = phnNum;
		this.mobNum = mobNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CFTRA_ID", unique = true, nullable = false)
	public Long getCftraId() {
		return this.cftraId;
	}

	public void setCftraId(Long cftraId) {
		this.cftraId = cftraId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_ID", nullable = false)
	public Schl getSchl() {
		return this.schl;
	}

	public void setSchl(Schl schl) {
		this.schl = schl;
	}

	@Column(name = "NME", length = 45)
	public String getNme() {
		return this.nme;
	}

	public void setNme(String nme) {
		this.nme = nme;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHN_NUM", length = 45)
	public String getPhnNum() {
		return this.phnNum;
	}

	public void setPhnNum(String phnNum) {
		this.phnNum = phnNum;
	}

	@Column(name = "MOB_NUM", length = 45)
	public String getMobNum() {
		return this.mobNum;
	}

	public void setMobNum(String mobNum) {
		this.mobNum = mobNum;
	}

}
