package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClstrDat generated by hbm2java
 */
@Entity
@Table(name = "clstr_dat", catalog = "saas_core_db")
public class ClstrDat extends AbstractAuditEntity {

	private Integer clstrDatId;
	private String host;
	private String httpPort;
	private String httpsPort;
	private String akkaPort;
	private String tcpPort;
	private String appNme;
	private String dmnNme;
	private String srvrNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;

	public ClstrDat() {
	}

	public ClstrDat(String host, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.host = host;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public ClstrDat(String host, String httpPort, String httpsPort, String akkaPort, String tcpPort, String appNme,
			String dmnNme, String srvrNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.host = host;
		this.httpPort = httpPort;
		this.httpsPort = httpsPort;
		this.akkaPort = akkaPort;
		this.tcpPort = tcpPort;
		this.appNme = appNme;
		this.dmnNme = dmnNme;
		this.srvrNme = srvrNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "CLSTR_DAT_ID", unique = true, nullable = false)
	public Integer getClstrDatId() {
		return this.clstrDatId;
	}

	public void setClstrDatId(Integer clstrDatId) {
		this.clstrDatId = clstrDatId;
	}

	@Column(name = "HOST", nullable = false, length = 45)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "HTTP_PORT", length = 45)
	public String getHttpPort() {
		return this.httpPort;
	}

	public void setHttpPort(String httpPort) {
		this.httpPort = httpPort;
	}

	@Column(name = "HTTPS_PORT", length = 45)
	public String getHttpsPort() {
		return this.httpsPort;
	}

	public void setHttpsPort(String httpsPort) {
		this.httpsPort = httpsPort;
	}

	@Column(name = "AKKA_PORT", length = 45)
	public String getAkkaPort() {
		return this.akkaPort;
	}

	public void setAkkaPort(String akkaPort) {
		this.akkaPort = akkaPort;
	}

	@Column(name = "TCP_PORT", length = 45)
	public String getTcpPort() {
		return this.tcpPort;
	}

	public void setTcpPort(String tcpPort) {
		this.tcpPort = tcpPort;
	}

	@Column(name = "APP_NME", length = 45)
	public String getAppNme() {
		return this.appNme;
	}

	public void setAppNme(String appNme) {
		this.appNme = appNme;
	}

	@Column(name = "DMN_NME", length = 45)
	public String getDmnNme() {
		return this.dmnNme;
	}

	public void setDmnNme(String dmnNme) {
		this.dmnNme = dmnNme;
	}

	@Column(name = "SRVR_NME", length = 45)
	public String getSrvrNme() {
		return this.srvrNme;
	}

	public void setSrvrNme(String srvrNme) {
		this.srvrNme = srvrNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

}
