package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DvsnTchrSujctMap generated by hbm2java
 */
@Entity
@Table(name = "dvsn_tchr_sujct_map", catalog = "saas_core_db")
public class DvsnTchrSujctMap extends AbstractAuditEntity {

	private Long dvsnTchrSujctMapId;
	private DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap;
	private SbjctTchrMap sbjctTchrMap;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public DvsnTchrSujctMap() {
	}

	public DvsnTchrSujctMap(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap, SbjctTchrMap sbjctTchrMap, String crtdUsr,
			Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
		this.sbjctTchrMap = sbjctTchrMap;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DVSN_TCHR_SUJCT_MAP_ID", unique = true, nullable = false)
	public Long getDvsnTchrSujctMapId() {
		return this.dvsnTchrSujctMapId;
	}

	public void setDvsnTchrSujctMapId(Long dvsnTchrSujctMapId) {
		this.dvsnTchrSujctMapId = dvsnTchrSujctMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVSN_SCHL_GRD_LVL_MAP_ID", nullable = false)
	public DvsnSchlGrdLvlMap getDvsnSchlGrdLvlMap() {
		return this.dvsnSchlGrdLvlMap;
	}

	public void setDvsnSchlGrdLvlMap(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBJCT_TCHR_MAP_ID", nullable = false)
	public SbjctTchrMap getSbjctTchrMap() {
		return this.sbjctTchrMap;
	}

	public void setSbjctTchrMap(SbjctTchrMap sbjctTchrMap) {
		this.sbjctTchrMap = sbjctTchrMap;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
