package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DvsnSchlGrdLvlMap generated by hbm2java
 */
@Entity
@Table(name = "dvsn_schl_grd_lvl_map", catalog = "saas_core_db")
public class DvsnSchlGrdLvlMap extends AbstractAuditEntity {

	private Integer dvsnSchlGrdLvlMapId;
	private Dvsn dvsn;
	private SchlGrdLvlMap schlGrdLvlMap;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;
	private Set<DvsnTchrSujctMap> dvsnTchrSujctMaps = new HashSet<DvsnTchrSujctMap>(0);
	private Set<Tchr> tchrs = new HashSet<Tchr>(0);
	private Set<Stdnt> stdnts = new HashSet<Stdnt>(0);

	public DvsnSchlGrdLvlMap() {
	}

	public DvsnSchlGrdLvlMap(Dvsn dvsn, SchlGrdLvlMap schlGrdLvlMap, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.dvsn = dvsn;
		this.schlGrdLvlMap = schlGrdLvlMap;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public DvsnSchlGrdLvlMap(Dvsn dvsn, SchlGrdLvlMap schlGrdLvlMap, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm, Set<DvsnTchrSujctMap> dvsnTchrSujctMaps, Set<Tchr> tchrs, Set<Stdnt> stdnts) {
		this.dvsn = dvsn;
		this.schlGrdLvlMap = schlGrdLvlMap;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.dvsnTchrSujctMaps = dvsnTchrSujctMaps;
		this.tchrs = tchrs;
		this.stdnts = stdnts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DVSN_SCHL_GRD_LVL_MAP_ID", unique = true, nullable = false)
	public Integer getDvsnSchlGrdLvlMapId() {
		return this.dvsnSchlGrdLvlMapId;
	}

	public void setDvsnSchlGrdLvlMapId(Integer dvsnSchlGrdLvlMapId) {
		this.dvsnSchlGrdLvlMapId = dvsnSchlGrdLvlMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVSN_ID", nullable = false)
	public Dvsn getDvsn() {
		return this.dvsn;
	}

	public void setDvsn(Dvsn dvsn) {
		this.dvsn = dvsn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_GRD_LVL_MAP_ID", nullable = false)
	public SchlGrdLvlMap getSchlGrdLvlMap() {
		return this.schlGrdLvlMap;
	}

	public void setSchlGrdLvlMap(SchlGrdLvlMap schlGrdLvlMap) {
		this.schlGrdLvlMap = schlGrdLvlMap;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dvsnSchlGrdLvlMap")
	public Set<DvsnTchrSujctMap> getDvsnTchrSujctMaps() {
		return this.dvsnTchrSujctMaps;
	}

	public void setDvsnTchrSujctMaps(Set<DvsnTchrSujctMap> dvsnTchrSujctMaps) {
		this.dvsnTchrSujctMaps = dvsnTchrSujctMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dvsnSchlGrdLvlMap")
	public Set<Tchr> getTchrs() {
		return this.tchrs;
	}

	public void setTchrs(Set<Tchr> tchrs) {
		this.tchrs = tchrs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dvsnSchlGrdLvlMap")
	public Set<Stdnt> getStdnts() {
		return this.stdnts;
	}

	public void setStdnts(Set<Stdnt> stdnts) {
		this.stdnts = stdnts;
	}

}
