package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dvsn generated by hbm2java
 */
@Entity
@Table(name = "dvsn", catalog = "saas_core_db", uniqueConstraints = @UniqueConstraint(columnNames = "DVSN_NME"))
public class Dvsn extends AbstractAuditEntity {

	private Long dvsnId;
	private String dvsnNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<DvsnSchlGrdLvlMap> dvsnSchlGrdLvlMaps = new HashSet<DvsnSchlGrdLvlMap>(0);

	public Dvsn() {
	}

	public Dvsn(String dvsnNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.dvsnNme = dvsnNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public Dvsn(String dvsnNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr,
			Set<DvsnSchlGrdLvlMap> dvsnSchlGrdLvlMaps) {
		this.dvsnNme = dvsnNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.dvsnSchlGrdLvlMaps = dvsnSchlGrdLvlMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DVSN_ID", unique = true, nullable = false)
	public Long getDvsnId() {
		return this.dvsnId;
	}

	public void setDvsnId(Long dvsnId) {
		this.dvsnId = dvsnId;
	}

	@Column(name = "DVSN_NME", unique = true, nullable = false, length = 45)
	public String getDvsnNme() {
		return this.dvsnNme;
	}

	public void setDvsnNme(String dvsnNme) {
		this.dvsnNme = dvsnNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dvsn")
	public Set<DvsnSchlGrdLvlMap> getDvsnSchlGrdLvlMaps() {
		return this.dvsnSchlGrdLvlMaps;
	}

	public void setDvsnSchlGrdLvlMaps(Set<DvsnSchlGrdLvlMap> dvsnSchlGrdLvlMaps) {
		this.dvsnSchlGrdLvlMaps = dvsnSchlGrdLvlMaps;
	}

}
