package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmgCtct generated by hbm2java
 */
@Entity
@Table(name = "emg_ctct", catalog = "saas_core_db")
public class EmgCtct extends AbstractAuditEntity {

	private Integer emgCtctId;
	private String fstNme;
	private String lstNme;
	private String email;
	private Integer actInd;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;
	private Set<Stdnt> stdnts = new HashSet<Stdnt>(0);

	public EmgCtct() {
	}

	public EmgCtct(String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public EmgCtct(String fstNme, String lstNme, String email, Integer actInd, String crtdUsr, Date crtdDttm,
			String lstUptdUsr, Date lstUptdDttm, Set<Stdnt> stdnts) {
		this.fstNme = fstNme;
		this.lstNme = lstNme;
		this.email = email;
		this.actInd = actInd;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.stdnts = stdnts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EMG_CTCT_ID", unique = true, nullable = false)
	public Integer getEmgCtctId() {
		return this.emgCtctId;
	}

	public void setEmgCtctId(Integer emgCtctId) {
		this.emgCtctId = emgCtctId;
	}

	@Column(name = "FST_NME", length = 45)
	public String getFstNme() {
		return this.fstNme;
	}

	public void setFstNme(String fstNme) {
		this.fstNme = fstNme;
	}

	@Column(name = "LST_NME", length = 45)
	public String getLstNme() {
		return this.lstNme;
	}

	public void setLstNme(String lstNme) {
		this.lstNme = lstNme;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ACT_IND")
	public Integer getActInd() {
		return this.actInd;
	}

	public void setActInd(Integer actInd) {
		this.actInd = actInd;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "emgCtct")
	public Set<Stdnt> getStdnts() {
		return this.stdnts;
	}

	public void setStdnts(Set<Stdnt> stdnts) {
		this.stdnts = stdnts;
	}

}
