package com.saas.edu.dao.model;
// Generated Jun 17, 2017 11:44:09 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmgcCtct generated by hbm2java
 */
@Entity
@Table(name = "emgc_ctct", catalog = "saas_core_db")
public class EmgcCtct extends AbstractAuditEntity {

	private long emgcCtctId;
	private Stdnt stdnt;
	private String fstNme;
	private String lstNme;
	private String email;
	private String phnNbr;

	public EmgcCtct() {
	}

	public EmgcCtct(long emgcCtctId, Stdnt stdnt) {
		this.emgcCtctId = emgcCtctId;
		this.stdnt = stdnt;
	}

	public EmgcCtct(long emgcCtctId, Stdnt stdnt, String fstNme, String lstNme, String email, String phnNbr) {
		this.emgcCtctId = emgcCtctId;
		this.stdnt = stdnt;
		this.fstNme = fstNme;
		this.lstNme = lstNme;
		this.email = email;
		this.phnNbr = phnNbr;
	}

	@Id

	@Column(name = "EMGC_CTCT_ID", unique = true, nullable = false)
	public long getEmgcCtctId() {
		return this.emgcCtctId;
	}

	public void setEmgcCtctId(long emgcCtctId) {
		this.emgcCtctId = emgcCtctId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stdnt_STDNT_ID", nullable = false)
	public Stdnt getStdnt() {
		return this.stdnt;
	}

	public void setStdnt(Stdnt stdnt) {
		this.stdnt = stdnt;
	}

	@Column(name = "FST_NME", length = 45)
	public String getFstNme() {
		return this.fstNme;
	}

	public void setFstNme(String fstNme) {
		this.fstNme = fstNme;
	}

	@Column(name = "LST_NME", length = 45)
	public String getLstNme() {
		return this.lstNme;
	}

	public void setLstNme(String lstNme) {
		this.lstNme = lstNme;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHN_NBR", length = 45)
	public String getPhnNbr() {
		return this.phnNbr;
	}

	public void setPhnNbr(String phnNbr) {
		this.phnNbr = phnNbr;
	}

}
