package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exm generated by hbm2java
 */
@Entity
@Table(name = "exm", catalog = "saas_core_db")
public class Exm extends AbstractAuditEntity {

	private Long exmId;
	private ExmGrp exmGrp;
	private SchlSbjctMap schlSbjctMap;
	private String mxmMrk;
	private String exmCdeNme;
	private Date dteOfExm;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<MrkLst> mrkLsts = new HashSet<MrkLst>(0);

	public Exm() {
	}

	public Exm(ExmGrp exmGrp, SchlSbjctMap schlSbjctMap, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr) {
		this.exmGrp = exmGrp;
		this.schlSbjctMap = schlSbjctMap;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public Exm(ExmGrp exmGrp, SchlSbjctMap schlSbjctMap, String mxmMrk, String exmCdeNme, Date dteOfExm, Date crtdDttm,
			String crtdUsr, Date lstUptdDttm, String lstUptdUsr, Set<MrkLst> mrkLsts) {
		this.exmGrp = exmGrp;
		this.schlSbjctMap = schlSbjctMap;
		this.mxmMrk = mxmMrk;
		this.exmCdeNme = exmCdeNme;
		this.dteOfExm = dteOfExm;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.mrkLsts = mrkLsts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "EXM_ID", unique = true, nullable = false)
	public Long getExmId() {
		return this.exmId;
	}

	public void setExmId(Long exmId) {
		this.exmId = exmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXM_GRP_ID", nullable = false)
	public ExmGrp getExmGrp() {
		return this.exmGrp;
	}

	public void setExmGrp(ExmGrp exmGrp) {
		this.exmGrp = exmGrp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_SBJCT_MAP_ID", nullable = false)
	public SchlSbjctMap getSchlSbjctMap() {
		return this.schlSbjctMap;
	}

	public void setSchlSbjctMap(SchlSbjctMap schlSbjctMap) {
		this.schlSbjctMap = schlSbjctMap;
	}

	@Column(name = "MXM_MRK", length = 45)
	public String getMxmMrk() {
		return this.mxmMrk;
	}

	public void setMxmMrk(String mxmMrk) {
		this.mxmMrk = mxmMrk;
	}

	@Column(name = "EXM_CDE_NME", length = 45)
	public String getExmCdeNme() {
		return this.exmCdeNme;
	}

	public void setExmCdeNme(String exmCdeNme) {
		this.exmCdeNme = exmCdeNme;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DTE_OF_EXM", length = 10)
	public Date getDteOfExm() {
		return this.dteOfExm;
	}

	public void setDteOfExm(Date dteOfExm) {
		this.dteOfExm = dteOfExm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exm")
	public Set<MrkLst> getMrkLsts() {
		return this.mrkLsts;
	}

	public void setMrkLsts(Set<MrkLst> mrkLsts) {
		this.mrkLsts = mrkLsts;
	}

}
