package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * GrdLvl generated by hbm2java
 */
@Entity
@Table(name = "grd_lvl", catalog = "saas_core_db", uniqueConstraints = @UniqueConstraint(columnNames = "GRD_NME"))
public class GrdLvl extends AbstractAuditEntity {

	private Long grdLvlId;
	private String grdNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<SchlGrdLvlMap> schlGrdLvlMaps = new HashSet<SchlGrdLvlMap>(0);

	public GrdLvl() {
	}

	public GrdLvl(String grdNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.grdNme = grdNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public GrdLvl(String grdNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr,
			Set<SchlGrdLvlMap> schlGrdLvlMaps) {
		this.grdNme = grdNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.schlGrdLvlMaps = schlGrdLvlMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "GRD_LVL_ID", unique = true, nullable = false)
	public Long getGrdLvlId() {
		return this.grdLvlId;
	}

	public void setGrdLvlId(Long grdLvlId) {
		this.grdLvlId = grdLvlId;
	}

	@Column(name = "GRD_NME", unique = true, nullable = false, length = 8)
	public String getGrdNme() {
		return this.grdNme;
	}

	public void setGrdNme(String grdNme) {
		this.grdNme = grdNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grdLvl")
	public Set<SchlGrdLvlMap> getSchlGrdLvlMaps() {
		return this.schlGrdLvlMaps;
	}

	public void setSchlGrdLvlMaps(Set<SchlGrdLvlMap> schlGrdLvlMaps) {
		this.schlGrdLvlMaps = schlGrdLvlMaps;
	}

}
