package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MrkLst generated by hbm2java
 */
@Entity
@Table(name = "mrk_lst", catalog = "saas_core_db")
public class MrkLst extends AbstractAuditEntity {

	private Long mrkLstId;
	private Exm exm;
	private Stdnt stdnt;
	private String mrk;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private String maxMrk;

	public MrkLst() {
	}

	public MrkLst(Exm exm, Stdnt stdnt, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.exm = exm;
		this.stdnt = stdnt;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public MrkLst(Exm exm, Stdnt stdnt, String mrk, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr,
			String maxMrk) {
		this.exm = exm;
		this.stdnt = stdnt;
		this.mrk = mrk;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.maxMrk = maxMrk;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MRK_LST_ID", unique = true, nullable = false)
	public Long getMrkLstId() {
		return this.mrkLstId;
	}

	public void setMrkLstId(Long mrkLstId) {
		this.mrkLstId = mrkLstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXM_ID", nullable = false)
	public Exm getExm() {
		return this.exm;
	}

	public void setExm(Exm exm) {
		this.exm = exm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STDNT_ID", nullable = false)
	public Stdnt getStdnt() {
		return this.stdnt;
	}

	public void setStdnt(Stdnt stdnt) {
		this.stdnt = stdnt;
	}

	@Column(name = "MRK", length = 8)
	public String getMrk() {
		return this.mrk;
	}

	public void setMrk(String mrk) {
		this.mrk = mrk;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Column(name = "MAX_MRK", length = 45)
	public String getMaxMrk() {
		return this.maxMrk;
	}

	public void setMaxMrk(String maxMrk) {
		this.maxMrk = maxMrk;
	}

}
