package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NtfnType generated by hbm2java
 */
@Entity
@Table(name = "ntfn_type", catalog = "saas_core_db")
public class NtfnType extends AbstractAuditEntity {

	private Long ntfnTypeId;
	private String typeNme;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;
	private Set<Ntfn> ntfns = new HashSet<Ntfn>(0);

	public NtfnType() {
	}

	public NtfnType(String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public NtfnType(String typeNme, String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm,
			Set<Ntfn> ntfns) {
		this.typeNme = typeNme;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.ntfns = ntfns;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NTFN_TYPE_ID", unique = true, nullable = false)
	public Long getNtfnTypeId() {
		return this.ntfnTypeId;
	}

	public void setNtfnTypeId(Long ntfnTypeId) {
		this.ntfnTypeId = ntfnTypeId;
	}

	@Column(name = "TYPE_NME", length = 45)
	public String getTypeNme() {
		return this.typeNme;
	}

	public void setTypeNme(String typeNme) {
		this.typeNme = typeNme;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ntfnType")
	public Set<Ntfn> getNtfns() {
		return this.ntfns;
	}

	public void setNtfns(Set<Ntfn> ntfns) {
		this.ntfns = ntfns;
	}

}
