package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ntfn generated by hbm2java
 */
@Entity
@Table(name = "ntfn", catalog = "saas_core_db")
public class Ntfn extends AbstractAuditEntity {

	private long ntfnId;
	private NtfnType ntfnType;
	private Stdnt stdnt;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public Ntfn() {
	}

	public Ntfn(long ntfnId, NtfnType ntfnType, Stdnt stdnt, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.ntfnId = ntfnId;
		this.ntfnType = ntfnType;
		this.stdnt = stdnt;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id

	@Column(name = "NTFN_ID", unique = true, nullable = false)
	public long getNtfnId() {
		return this.ntfnId;
	}

	public void setNtfnId(long ntfnId) {
		this.ntfnId = ntfnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NTFN_TYPE_ID", nullable = false)
	public NtfnType getNtfnType() {
		return this.ntfnType;
	}

	public void setNtfnType(NtfnType ntfnType) {
		this.ntfnType = ntfnType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STDNT_ID", nullable = false)
	public Stdnt getStdnt() {
		return this.stdnt;
	}

	public void setStdnt(Stdnt stdnt) {
		this.stdnt = stdnt;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
