package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Prnt generated by hbm2java
 */
@Entity
@Table(name = "prnt", catalog = "saas_core_db")
public class Prnt extends AbstractAuditEntity {

	private long prntId;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Integer prntPri;
	private Integer actvInd;
	private Set<PrntLognAtmt> prntLognAtmts = new HashSet<PrntLognAtmt>(0);
	private Set<PrntAuth> prntAuths = new HashSet<PrntAuth>(0);
	private Set<StdntPrntMap> stdntPrntMaps = new HashSet<StdntPrntMap>(0);
	private Set<PrntCntctDet> prntCntctDets = new HashSet<PrntCntctDet>(0);
	private Set<PrntDevc> prntDevcs = new HashSet<PrntDevc>(0);

	public Prnt() {
	}

	public Prnt(long prntId, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.prntId = prntId;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public Prnt(long prntId, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr, Integer prntPri,
			Integer actvInd, Set<PrntLognAtmt> prntLognAtmts, Set<PrntAuth> prntAuths, Set<StdntPrntMap> stdntPrntMaps,
			Set<PrntCntctDet> prntCntctDets, Set<PrntDevc> prntDevcs) {
		this.prntId = prntId;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.prntPri = prntPri;
		this.actvInd = actvInd;
		this.prntLognAtmts = prntLognAtmts;
		this.prntAuths = prntAuths;
		this.stdntPrntMaps = stdntPrntMaps;
		this.prntCntctDets = prntCntctDets;
		this.prntDevcs = prntDevcs;
	}

	@Id

	@Column(name = "PRNT_ID", unique = true, nullable = false)
	public long getPrntId() {
		return this.prntId;
	}

	public void setPrntId(long prntId) {
		this.prntId = prntId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Column(name = "PRNT_PRI")
	public Integer getPrntPri() {
		return this.prntPri;
	}

	public void setPrntPri(Integer prntPri) {
		this.prntPri = prntPri;
	}

	@Column(name = "ACTV_IND")
	public Integer getActvInd() {
		return this.actvInd;
	}

	public void setActvInd(Integer actvInd) {
		this.actvInd = actvInd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prnt")
	public Set<PrntLognAtmt> getPrntLognAtmts() {
		return this.prntLognAtmts;
	}

	public void setPrntLognAtmts(Set<PrntLognAtmt> prntLognAtmts) {
		this.prntLognAtmts = prntLognAtmts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prnt")
	public Set<PrntAuth> getPrntAuths() {
		return this.prntAuths;
	}

	public void setPrntAuths(Set<PrntAuth> prntAuths) {
		this.prntAuths = prntAuths;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prnt")
	public Set<StdntPrntMap> getStdntPrntMaps() {
		return this.stdntPrntMaps;
	}

	public void setStdntPrntMaps(Set<StdntPrntMap> stdntPrntMaps) {
		this.stdntPrntMaps = stdntPrntMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prnt")
	public Set<PrntCntctDet> getPrntCntctDets() {
		return this.prntCntctDets;
	}

	public void setPrntCntctDets(Set<PrntCntctDet> prntCntctDets) {
		this.prntCntctDets = prntCntctDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "prnt")
	public Set<PrntDevc> getPrntDevcs() {
		return this.prntDevcs;
	}

	public void setPrntDevcs(Set<PrntDevc> prntDevcs) {
		this.prntDevcs = prntDevcs;
	}

}
