package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrntCntctDet generated by hbm2java
 */
@Entity
@Table(name = "prnt_cntct_det", catalog = "saas_core_db")
public class PrntCntctDet extends AbstractAuditEntity {

	private Long prntCntctDetId;
	private Prnt prnt;
	private String fstNme;
	private String lstNme;
	private String prntCtctType;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private String email;
	private String phnNum;
	private String mobNum;
	private String address;

	public PrntCntctDet() {
	}

	public PrntCntctDet(Prnt prnt, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.prnt = prnt;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public PrntCntctDet(Prnt prnt, String fstNme, String lstNme, String prntCtctType, Date crtdDttm, String crtdUsr,
			Date lstUptdDttm, String lstUptdUsr, String email, String phnNum, String mobNum, String address) {
		this.prnt = prnt;
		this.fstNme = fstNme;
		this.lstNme = lstNme;
		this.prntCtctType = prntCtctType;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.email = email;
		this.phnNum = phnNum;
		this.mobNum = mobNum;
		this.address = address;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRNT_CNTCT_DET_ID", unique = true, nullable = false)
	public Long getPrntCntctDetId() {
		return this.prntCntctDetId;
	}

	public void setPrntCntctDetId(Long prntCntctDetId) {
		this.prntCntctDetId = prntCntctDetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_ID", nullable = false)
	public Prnt getPrnt() {
		return this.prnt;
	}

	public void setPrnt(Prnt prnt) {
		this.prnt = prnt;
	}

	@Column(name = "FST_NME", length = 45)
	public String getFstNme() {
		return this.fstNme;
	}

	public void setFstNme(String fstNme) {
		this.fstNme = fstNme;
	}

	@Column(name = "LST_NME", length = 45)
	public String getLstNme() {
		return this.lstNme;
	}

	public void setLstNme(String lstNme) {
		this.lstNme = lstNme;
	}

	@Column(name = "PRNT_CTCT_TYPE", length = 45)
	public String getPrntCtctType() {
		return this.prntCtctType;
	}

	public void setPrntCtctType(String prntCtctType) {
		this.prntCtctType = prntCtctType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Column(name = "EMAIL", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PHN_NUM", length = 45)
	public String getPhnNum() {
		return this.phnNum;
	}

	public void setPhnNum(String phnNum) {
		this.phnNum = phnNum;
	}

	@Column(name = "MOB_NUM", length = 45)
	public String getMobNum() {
		return this.mobNum;
	}

	public void setMobNum(String mobNum) {
		this.mobNum = mobNum;
	}

	@Column(name = "ADDRESS", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
