package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrntLognAtmt generated by hbm2java
 */
@Entity
@Table(name = "prnt_logn_atmt", catalog = "saas_core_db")
public class PrntLognAtmt extends AbstractAuditEntity {

	private Integer prntUsrLognId;
	private Prnt prnt;
	private Character loginStatus;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public PrntLognAtmt() {
	}

	public PrntLognAtmt(Prnt prnt, String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.prnt = prnt;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public PrntLognAtmt(Prnt prnt, Character loginStatus, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.prnt = prnt;
		this.loginStatus = loginStatus;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRNT_USR_LOGN_ID", unique = true, nullable = false)
	public Integer getPrntUsrLognId() {
		return this.prntUsrLognId;
	}

	public void setPrntUsrLognId(Integer prntUsrLognId) {
		this.prntUsrLognId = prntUsrLognId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_ID", nullable = false)
	public Prnt getPrnt() {
		return this.prnt;
	}

	public void setPrnt(Prnt prnt) {
		this.prnt = prnt;
	}

	@Column(name = "LOGIN_STATUS", length = 1)
	public Character getLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(Character loginStatus) {
		this.loginStatus = loginStatus;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 15)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 15)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
