package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PrntDevc generated by hbm2java
 */
@Entity
@Table(name = "prnt_devc", catalog = "saas_core_db")
public class PrntDevc extends AbstractAuditEntity {

	private Long prntDevcId;
	private Prnt prnt;
	private String devcType;
	private String regCod;
	private String ntfnPref;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public PrntDevc() {
	}

	public PrntDevc(Prnt prnt, String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.prnt = prnt;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public PrntDevc(Prnt prnt, String devcType, String regCod, String ntfnPref, String crtdUsr, Date crtdDttm,
			String lstUptdUsr, Date lstUptdDttm) {
		this.prnt = prnt;
		this.devcType = devcType;
		this.regCod = regCod;
		this.ntfnPref = ntfnPref;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRNT_DEVC_ID", unique = true, nullable = false)
	public Long getPrntDevcId() {
		return this.prntDevcId;
	}

	public void setPrntDevcId(Long prntDevcId) {
		this.prntDevcId = prntDevcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_ID", nullable = false)
	public Prnt getPrnt() {
		return this.prnt;
	}

	public void setPrnt(Prnt prnt) {
		this.prnt = prnt;
	}

	@Column(name = "DEVC_TYPE", length = 45)
	public String getDevcType() {
		return this.devcType;
	}

	public void setDevcType(String devcType) {
		this.devcType = devcType;
	}

	@Column(name = "REG_COD", length = 45)
	public String getRegCod() {
		return this.regCod;
	}

	public void setRegCod(String regCod) {
		this.regCod = regCod;
	}

	@Column(name = "NTFN_PREF", length = 8)
	public String getNtfnPref() {
		return this.ntfnPref;
	}

	public void setNtfnPref(String ntfnPref) {
		this.ntfnPref = ntfnPref;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
