package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PrntAuth generated by hbm2java
 */
@Entity
@Table(name = "prnt_auth", catalog = "saas_core_db", uniqueConstraints = @UniqueConstraint(columnNames = "LGN_NME"))
public class PrntAuth extends AbstractAuditEntity {

	private Long prntAuthId;
	private Prnt prnt;
	private String lgnNme;
	private String pswd;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public PrntAuth() {
	}

	public PrntAuth(Prnt prnt, String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.prnt = prnt;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public PrntAuth(Prnt prnt, String lgnNme, String pswd, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.prnt = prnt;
		this.lgnNme = lgnNme;
		this.pswd = pswd;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PRNT_AUTH_ID", unique = true, nullable = false)
	public Long getPrntAuthId() {
		return this.prntAuthId;
	}

	public void setPrntAuthId(Long prntAuthId) {
		this.prntAuthId = prntAuthId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_ID", nullable = false)
	public Prnt getPrnt() {
		return this.prnt;
	}

	public void setPrnt(Prnt prnt) {
		this.prnt = prnt;
	}

	@Column(name = "LGN_NME", unique = true, length = 45)
	public String getLgnNme() {
		return this.lgnNme;
	}

	public void setLgnNme(String lgnNme) {
		this.lgnNme = lgnNme;
	}

	@Column(name = "PSWD", length = 45)
	public String getPswd() {
		return this.pswd;
	}

	public void setPswd(String pswd) {
		this.pswd = pswd;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
