package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SbjctTchrMap generated by hbm2java
 */
@Entity
@Table(name = "sbjct_tchr_map", catalog = "saas_core_db")
public class SbjctTchrMap extends AbstractAuditEntity {

	private Long sbjctTchrMapId;
	private SchlSbjctMap schlSbjctMap;
	private Tchr tchr;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<DvsnTchrSujctMap> dvsnTchrSujctMaps = new HashSet<DvsnTchrSujctMap>(0);

	public SbjctTchrMap() {
	}

	public SbjctTchrMap(SchlSbjctMap schlSbjctMap, Tchr tchr, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr) {
		this.schlSbjctMap = schlSbjctMap;
		this.tchr = tchr;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public SbjctTchrMap(SchlSbjctMap schlSbjctMap, Tchr tchr, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr, Set<DvsnTchrSujctMap> dvsnTchrSujctMaps) {
		this.schlSbjctMap = schlSbjctMap;
		this.tchr = tchr;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.dvsnTchrSujctMaps = dvsnTchrSujctMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SBJCT_TCHR_MAP_ID", unique = true, nullable = false)
	public Long getSbjctTchrMapId() {
		return this.sbjctTchrMapId;
	}

	public void setSbjctTchrMapId(Long sbjctTchrMapId) {
		this.sbjctTchrMapId = sbjctTchrMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_SBJCT_MAP_ID", nullable = false)
	public SchlSbjctMap getSchlSbjctMap() {
		return this.schlSbjctMap;
	}

	public void setSchlSbjctMap(SchlSbjctMap schlSbjctMap) {
		this.schlSbjctMap = schlSbjctMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TCHR_ID", nullable = false)
	public Tchr getTchr() {
		return this.tchr;
	}

	public void setTchr(Tchr tchr) {
		this.tchr = tchr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sbjctTchrMap")
	public Set<DvsnTchrSujctMap> getDvsnTchrSujctMaps() {
		return this.dvsnTchrSujctMaps;
	}

	public void setDvsnTchrSujctMaps(Set<DvsnTchrSujctMap> dvsnTchrSujctMaps) {
		this.dvsnTchrSujctMaps = dvsnTchrSujctMaps;
	}

}
