package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sbjct generated by hbm2java
 */
@Entity
@Table(name = "sbjct", catalog = "saas_core_db")
public class Sbjct extends AbstractAuditEntity {

	private Long sbjctId;
	private String sbjctNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<SchlSbjctMap> schlSbjctMaps = new HashSet<SchlSbjctMap>(0);

	public Sbjct() {
	}

	public Sbjct(Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public Sbjct(String sbjctNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr,
			Set<SchlSbjctMap> schlSbjctMaps) {
		this.sbjctNme = sbjctNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.schlSbjctMaps = schlSbjctMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SBJCT_ID", unique = true, nullable = false)
	public Long getSbjctId() {
		return this.sbjctId;
	}

	public void setSbjctId(Long sbjctId) {
		this.sbjctId = sbjctId;
	}

	@Column(name = "SBJCT_NME", length = 45)
	public String getSbjctNme() {
		return this.sbjctNme;
	}

	public void setSbjctNme(String sbjctNme) {
		this.sbjctNme = sbjctNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sbjct")
	public Set<SchlSbjctMap> getSchlSbjctMaps() {
		return this.schlSbjctMaps;
	}

	public void setSchlSbjctMaps(Set<SchlSbjctMap> schlSbjctMaps) {
		this.schlSbjctMaps = schlSbjctMaps;
	}

}
