package com.saas.edu.dao.model;
// Generated Jul 11, 2017 11:17:19 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlUsrLognAtmt generated by hbm2java
 */
@Entity
@Table(name = "schl_usr_logn_atmt", catalog = "saas_core_db")
public class SchlUsrLognAtmt extends AbstractAuditEntity {

	private int sysUsrLognAtmtId;
	private SchlUsr schlUsr;
	private Character usrLoginStatus;
	private String crtdUsr;
	private Date crtdDttm;
	private Date lstUptdDttm;
	private String lstUptdUsr;

	public SchlUsrLognAtmt() {
	}

	public SchlUsrLognAtmt(int sysUsrLognAtmtId, SchlUsr schlUsr, String crtdUsr, Date crtdDttm, Date lstUptdDttm,
			String lstUptdUsr) {
		this.sysUsrLognAtmtId = sysUsrLognAtmtId;
		this.schlUsr = schlUsr;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public SchlUsrLognAtmt(int sysUsrLognAtmtId, SchlUsr schlUsr, Character usrLoginStatus, String crtdUsr,
			Date crtdDttm, Date lstUptdDttm, String lstUptdUsr) {
		this.sysUsrLognAtmtId = sysUsrLognAtmtId;
		this.schlUsr = schlUsr;
		this.usrLoginStatus = usrLoginStatus;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	@Id

	@Column(name = "SYS_USR_LOGN_ATMT_ID", unique = true, nullable = false)
	public int getSysUsrLognAtmtId() {
		return this.sysUsrLognAtmtId;
	}

	public void setSysUsrLognAtmtId(int sysUsrLognAtmtId) {
		this.sysUsrLognAtmtId = sysUsrLognAtmtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SchlUsr getSchlUsr() {
		return this.schlUsr;
	}

	public void setSchlUsr(SchlUsr schlUsr) {
		this.schlUsr = schlUsr;
	}

	@Column(name = "USR_LOGIN_STATUS", length = 1)
	public Character getUsrLoginStatus() {
		return this.usrLoginStatus;
	}

	public void setUsrLoginStatus(Character usrLoginStatus) {
		this.usrLoginStatus = usrLoginStatus;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 15)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

}
