package com.saas.edu.dao.model;
// Generated Jul 11, 2017 11:17:19 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlUsrProf generated by hbm2java
 */
@Entity
@Table(name = "schl_usr_prof", catalog = "saas_core_db")
public class SchlUsrProf extends AbstractAuditEntity {

	private Integer sysUsrProfId;
	private SchlUsr schlUsr;
	private String usrEml;
	private String usrPhn;
	private String fstNme;
	private String lstNme;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public SchlUsrProf() {
	}

	public SchlUsrProf(SchlUsr schlUsr, String usrEml, String usrPhn, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.schlUsr = schlUsr;
		this.usrEml = usrEml;
		this.usrPhn = usrPhn;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public SchlUsrProf(SchlUsr schlUsr, String usrEml, String usrPhn, String fstNme, String lstNme, String crtdUsr,
			Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.schlUsr = schlUsr;
		this.usrEml = usrEml;
		this.usrPhn = usrPhn;
		this.fstNme = fstNme;
		this.lstNme = lstNme;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_PROF_ID", unique = true, nullable = false)
	public Integer getSysUsrProfId() {
		return this.sysUsrProfId;
	}

	public void setSysUsrProfId(Integer sysUsrProfId) {
		this.sysUsrProfId = sysUsrProfId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SchlUsr getSchlUsr() {
		return this.schlUsr;
	}

	public void setSchlUsr(SchlUsr schlUsr) {
		this.schlUsr = schlUsr;
	}

	@Column(name = "USR_EML", nullable = false, length = 45)
	public String getUsrEml() {
		return this.usrEml;
	}

	public void setUsrEml(String usrEml) {
		this.usrEml = usrEml;
	}

	@Column(name = "USR_PHN", nullable = false, length = 45)
	public String getUsrPhn() {
		return this.usrPhn;
	}

	public void setUsrPhn(String usrPhn) {
		this.usrPhn = usrPhn;
	}

	@Column(name = "FST_NME", length = 45)
	public String getFstNme() {
		return this.fstNme;
	}

	public void setFstNme(String fstNme) {
		this.fstNme = fstNme;
	}

	@Column(name = "LST_NME", length = 45)
	public String getLstNme() {
		return this.lstNme;
	}

	public void setLstNme(String lstNme) {
		this.lstNme = lstNme;
	}

	@Column(name = "CRTD_USR", length = 15)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 15)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
