package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlCtctDet generated by hbm2java
 */
@Entity
@Table(name = "schl_ctct_det", catalog = "saas_core_db")
public class SchlCtctDet extends AbstractAuditEntity {

	private Long schlCtctDetId;
	private Schl schl;
	private String schlNme;
	private String addr;
	private String city;
	private String district;
	private String state;
	private String pin;
	private String post;
	private String addrType;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;

	public SchlCtctDet() {
	}

	public SchlCtctDet(Schl schl, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.schl = schl;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public SchlCtctDet(Schl schl, String schlNme, String addr, String city, String district, String state, String pin,
			String post, String addrType, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.schl = schl;
		this.schlNme = schlNme;
		this.addr = addr;
		this.city = city;
		this.district = district;
		this.state = state;
		this.pin = pin;
		this.post = post;
		this.addrType = addrType;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SCHL_CTCT_DET_ID", unique = true, nullable = false)
	public Long getSchlCtctDetId() {
		return this.schlCtctDetId;
	}

	public void setSchlCtctDetId(Long schlCtctDetId) {
		this.schlCtctDetId = schlCtctDetId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_ID", nullable = false)
	public Schl getSchl() {
		return this.schl;
	}

	public void setSchl(Schl schl) {
		this.schl = schl;
	}

	@Column(name = "SCHL_NME", length = 45)
	public String getSchlNme() {
		return this.schlNme;
	}

	public void setSchlNme(String schlNme) {
		this.schlNme = schlNme;
	}

	@Column(name = "ADDR", length = 45)
	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

	@Column(name = "CITY", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "DISTRICT", length = 45)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "STATE", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "PIN", length = 45)
	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	@Column(name = "POST", length = 45)
	public String getPost() {
		return this.post;
	}

	public void setPost(String post) {
		this.post = post;
	}

	@Column(name = "ADDR_TYPE", length = 45)
	public String getAddrType() {
		return this.addrType;
	}

	public void setAddrType(String addrType) {
		this.addrType = addrType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

}
