package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlUsrRole generated by hbm2java
 */
@Entity
@Table(name = "schl_usr_role", catalog = "saas_core_db")
public class SchlUsrRole extends AbstractAuditEntity {

	private Integer sysUsrRoleId;
	private String roleNme;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public SchlUsrRole() {
	}

	public SchlUsrRole(String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public SchlUsrRole(String roleNme, String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.roleNme = roleNme;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_ROLE_ID", unique = true, nullable = false)
	public Integer getSysUsrRoleId() {
		return this.sysUsrRoleId;
	}

	public void setSysUsrRoleId(Integer sysUsrRoleId) {
		this.sysUsrRoleId = sysUsrRoleId;
	}

	@Column(name = "ROLE_NME", length = 45)
	public String getRoleNme() {
		return this.roleNme;
	}

	public void setRoleNme(String roleNme) {
		this.roleNme = roleNme;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 15)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 15)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
