package com.saas.edu.dao.model;
// Generated Jul 11, 2017 11:17:19 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlUsrLogn generated by hbm2java
 */
@Entity
@Table(name = "schl_usr_logn", catalog = "saas_core_db")
public class SchlUsrLogn extends AbstractAuditEntity {

	private Integer sysUsrLognId;
	private SchlUsr schlUsr;
	private String usrNme;
	private String usrPwd;
	private String usrStat;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;

	public SchlUsrLogn() {
	}

	public SchlUsrLogn(SchlUsr schlUsr, String usrNme, String usrStat, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.schlUsr = schlUsr;
		this.usrNme = usrNme;
		this.usrStat = usrStat;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public SchlUsrLogn(SchlUsr schlUsr, String usrNme, String usrPwd, String usrStat, String crtdUsr, Date crtdDttm,
			String lstUptdUsr, Date lstUptdDttm) {
		this.schlUsr = schlUsr;
		this.usrNme = usrNme;
		this.usrPwd = usrPwd;
		this.usrStat = usrStat;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_LOGN_ID", unique = true, nullable = false)
	public Integer getSysUsrLognId() {
		return this.sysUsrLognId;
	}

	public void setSysUsrLognId(Integer sysUsrLognId) {
		this.sysUsrLognId = sysUsrLognId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SchlUsr getSchlUsr() {
		return this.schlUsr;
	}

	public void setSchlUsr(SchlUsr schlUsr) {
		this.schlUsr = schlUsr;
	}

	@Column(name = "USR_NME", nullable = false, length = 45)
	public String getUsrNme() {
		return this.usrNme;
	}

	public void setUsrNme(String usrNme) {
		this.usrNme = usrNme;
	}

	@Column(name = "USR_PWD", length = 45)
	public String getUsrPwd() {
		return this.usrPwd;
	}

	public void setUsrPwd(String usrPwd) {
		this.usrPwd = usrPwd;
	}

	@Column(name = "USR_STAT", nullable = false, length = 10)
	public String getUsrStat() {
		return this.usrStat;
	}

	public void setUsrStat(String usrStat) {
		this.usrStat = usrStat;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 15)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 15)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

}
