package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Schl generated by hbm2java
 */
@Entity
@Table(name = "schl", catalog = "saas_core_db", uniqueConstraints = @UniqueConstraint(columnNames = "SCHL_CDE_NME"))
public class Schl extends AbstractAuditEntity {

	private Long schlId;
	private String schlCdeNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private int actvInd;
	private Set<Cftra> cftras = new HashSet<Cftra>(0);
	private Set<ExmGrp> exmGrps = new HashSet<ExmGrp>(0);
	private Set<SchlSbjctMap> schlSbjctMaps = new HashSet<SchlSbjctMap>(0);
	private Set<SchlCtctDet> schlCtctDets = new HashSet<SchlCtctDet>(0);
	private Set<SchlGrdLvlMap> schlGrdLvlMaps = new HashSet<SchlGrdLvlMap>(0);
	private Set<SchlUsr> schlUsrs = new HashSet<SchlUsr>(0);

	public Schl() {
	}

	public Schl(String schlCdeNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr, int actvInd) {
		this.schlCdeNme = schlCdeNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.actvInd = actvInd;
	}

	public Schl(String schlCdeNme, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr, int actvInd,
			Set<Cftra> cftras, Set<ExmGrp> exmGrps, Set<SchlSbjctMap> schlSbjctMaps, Set<SchlCtctDet> schlCtctDets,
			Set<SchlGrdLvlMap> schlGrdLvlMaps, Set<SchlUsr> schlUsrs) {
		this.schlCdeNme = schlCdeNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.actvInd = actvInd;
		this.cftras = cftras;
		this.exmGrps = exmGrps;
		this.schlSbjctMaps = schlSbjctMaps;
		this.schlCtctDets = schlCtctDets;
		this.schlGrdLvlMaps = schlGrdLvlMaps;
		this.schlUsrs = schlUsrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SCHL_ID", unique = true, nullable = false)
	public Long getSchlId() {
		return this.schlId;
	}

	public void setSchlId(Long schlId) {
		this.schlId = schlId;
	}

	@Column(name = "SCHL_CDE_NME", unique = true, nullable = false, length = 45)
	public String getSchlCdeNme() {
		return this.schlCdeNme;
	}

	public void setSchlCdeNme(String schlCdeNme) {
		this.schlCdeNme = schlCdeNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Column(name = "ACTV_IND", nullable = false)
	public int getActvInd() {
		return this.actvInd;
	}

	public void setActvInd(int actvInd) {
		this.actvInd = actvInd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schl")
	public Set<Cftra> getCftras() {
		return this.cftras;
	}

	public void setCftras(Set<Cftra> cftras) {
		this.cftras = cftras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schl")
	public Set<ExmGrp> getExmGrps() {
		return this.exmGrps;
	}

	public void setExmGrps(Set<ExmGrp> exmGrps) {
		this.exmGrps = exmGrps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schl")
	public Set<SchlSbjctMap> getSchlSbjctMaps() {
		return this.schlSbjctMaps;
	}

	public void setSchlSbjctMaps(Set<SchlSbjctMap> schlSbjctMaps) {
		this.schlSbjctMaps = schlSbjctMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schl")
	public Set<SchlCtctDet> getSchlCtctDets() {
		return this.schlCtctDets;
	}

	public void setSchlCtctDets(Set<SchlCtctDet> schlCtctDets) {
		this.schlCtctDets = schlCtctDets;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schl")
	public Set<SchlGrdLvlMap> getSchlGrdLvlMaps() {
		return this.schlGrdLvlMaps;
	}

	public void setSchlGrdLvlMaps(Set<SchlGrdLvlMap> schlGrdLvlMaps) {
		this.schlGrdLvlMaps = schlGrdLvlMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schl")
	public Set<SchlUsr> getSchlUsrs() {
		return this.schlUsrs;
	}

	public void setSchlUsrs(Set<SchlUsr> schlUsrs) {
		this.schlUsrs = schlUsrs;
	}

}
