package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlSbjctMap generated by hbm2java
 */
@Entity
@Table(name = "schl_sbjct_map", catalog = "saas_core_db")
public class SchlSbjctMap extends AbstractAuditEntity {

	private Long schlSbjctMapId;
	private Sbjct sbjct;
	private Schl schl;
	private String type;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;
	private Set<SbjctTchrMap> sbjctTchrMaps = new HashSet<SbjctTchrMap>(0);
	private Set<Exm> exms = new HashSet<Exm>(0);

	public SchlSbjctMap() {
	}

	public SchlSbjctMap(Sbjct sbjct, Schl schl, String crtdUsr, Date crtdDttm, String lstUptdUsr, Date lstUptdDttm) {
		this.sbjct = sbjct;
		this.schl = schl;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public SchlSbjctMap(Sbjct sbjct, Schl schl, String type, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm, Set<SbjctTchrMap> sbjctTchrMaps, Set<Exm> exms) {
		this.sbjct = sbjct;
		this.schl = schl;
		this.type = type;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.sbjctTchrMaps = sbjctTchrMaps;
		this.exms = exms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SCHL_SBJCT_MAP_ID", unique = true, nullable = false)
	public Long getSchlSbjctMapId() {
		return this.schlSbjctMapId;
	}

	public void setSchlSbjctMapId(Long schlSbjctMapId) {
		this.schlSbjctMapId = schlSbjctMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SBJCT_ID", nullable = false)
	public Sbjct getSbjct() {
		return this.sbjct;
	}

	public void setSbjct(Sbjct sbjct) {
		this.sbjct = sbjct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_ID", nullable = false)
	public Schl getSchl() {
		return this.schl;
	}

	public void setSchl(Schl schl) {
		this.schl = schl;
	}

	@Column(name = "TYPE", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schlSbjctMap")
	public Set<SbjctTchrMap> getSbjctTchrMaps() {
		return this.sbjctTchrMaps;
	}

	public void setSbjctTchrMaps(Set<SbjctTchrMap> sbjctTchrMaps) {
		this.sbjctTchrMaps = sbjctTchrMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schlSbjctMap")
	public Set<Exm> getExms() {
		return this.exms;
	}

	public void setExms(Set<Exm> exms) {
		this.exms = exms;
	}

}
