package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlGrdLvlMap generated by hbm2java
 */
@Entity
@Table(name = "schl_grd_lvl_map", catalog = "saas_core_db")
public class SchlGrdLvlMap extends AbstractAuditEntity {

	private Long schlGrdLvlMapId;
	private GrdLvl grdLvl;
	private Schl schl;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<DvsnSchlGrdLvlMap> dvsnSchlGrdLvlMaps = new HashSet<DvsnSchlGrdLvlMap>(0);

	public SchlGrdLvlMap() {
	}

	public SchlGrdLvlMap(GrdLvl grdLvl, Schl schl, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr) {
		this.grdLvl = grdLvl;
		this.schl = schl;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public SchlGrdLvlMap(GrdLvl grdLvl, Schl schl, Date crtdDttm, String crtdUsr, Date lstUptdDttm, String lstUptdUsr,
			Set<DvsnSchlGrdLvlMap> dvsnSchlGrdLvlMaps) {
		this.grdLvl = grdLvl;
		this.schl = schl;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.dvsnSchlGrdLvlMaps = dvsnSchlGrdLvlMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SCHL_GRD_LVL_MAP_ID", unique = true, nullable = false)
	public Long getSchlGrdLvlMapId() {
		return this.schlGrdLvlMapId;
	}

	public void setSchlGrdLvlMapId(Long schlGrdLvlMapId) {
		this.schlGrdLvlMapId = schlGrdLvlMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GRD_LVL_ID", nullable = false)
	public GrdLvl getGrdLvl() {
		return this.grdLvl;
	}

	public void setGrdLvl(GrdLvl grdLvl) {
		this.grdLvl = grdLvl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_ID", nullable = false)
	public Schl getSchl() {
		return this.schl;
	}

	public void setSchl(Schl schl) {
		this.schl = schl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schlGrdLvlMap")
	public Set<DvsnSchlGrdLvlMap> getDvsnSchlGrdLvlMaps() {
		return this.dvsnSchlGrdLvlMaps;
	}

	public void setDvsnSchlGrdLvlMaps(Set<DvsnSchlGrdLvlMap> dvsnSchlGrdLvlMaps) {
		this.dvsnSchlGrdLvlMaps = dvsnSchlGrdLvlMaps;
	}

}
