package com.saas.edu.dao.model;
// Generated Jul 11, 2017 11:17:19 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlUsrRoleMap generated by hbm2java
 */
@Entity
@Table(name = "schl_usr_role_map", catalog = "saas_core_db")
public class SchlUsrRoleMap extends AbstractAuditEntity {

	private Integer sysUsrRoleMapId;
	private SchlUsr schlUsr;
	private SchlUsrRole schlUsrRole;
	private String roleStatus;
	private String crtdUsr;
	private Date crtdDttm;
	private String lstUptdUsr;
	private Date lstUptdDttm;
	private String sysUsrRoleNme;

	public SchlUsrRoleMap() {
	}

	public SchlUsrRoleMap(SchlUsr schlUsr, SchlUsrRole schlUsrRole, String crtdUsr, Date crtdDttm, String lstUptdUsr,
			Date lstUptdDttm) {
		this.schlUsr = schlUsr;
		this.schlUsrRole = schlUsrRole;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
	}

	public SchlUsrRoleMap(SchlUsr schlUsr, SchlUsrRole schlUsrRole, String roleStatus, String crtdUsr, Date crtdDttm,
			String lstUptdUsr, Date lstUptdDttm, String sysUsrRoleNme) {
		this.schlUsr = schlUsr;
		this.schlUsrRole = schlUsrRole;
		this.roleStatus = roleStatus;
		this.crtdUsr = crtdUsr;
		this.crtdDttm = crtdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.sysUsrRoleNme = sysUsrRoleNme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_ROLE_MAP_ID", unique = true, nullable = false)
	public Integer getSysUsrRoleMapId() {
		return this.sysUsrRoleMapId;
	}

	public void setSysUsrRoleMapId(Integer sysUsrRoleMapId) {
		this.sysUsrRoleMapId = sysUsrRoleMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SchlUsr getSchlUsr() {
		return this.schlUsr;
	}

	public void setSchlUsr(SchlUsr schlUsr) {
		this.schlUsr = schlUsr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ROLE_ID", nullable = false)
	public SchlUsrRole getSchlUsrRole() {
		return this.schlUsrRole;
	}

	public void setSchlUsrRole(SchlUsrRole schlUsrRole) {
		this.schlUsrRole = schlUsrRole;
	}

	@Column(name = "ROLE_STATUS", length = 45)
	public String getRoleStatus() {
		return this.roleStatus;
	}

	public void setRoleStatus(String roleStatus) {
		this.roleStatus = roleStatus;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 15)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 15)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "SYS_USR_ROLE_NME", length = 45)
	public String getSysUsrRoleNme() {
		return this.sysUsrRoleNme;
	}

	public void setSysUsrRoleNme(String sysUsrRoleNme) {
		this.sysUsrRoleNme = sysUsrRoleNme;
	}

}
