package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SchlUsr generated by hbm2java
 */
@Entity
@Table(name = "schl_usr", catalog = "saas_core_db")
public class SchlUsr extends AbstractAuditEntity {

	private Integer schlUsrId;
	private Schl schl;
	private String idNbr;
	private String crtdByUssr;
	private Date crtdDttm;
	private String uptdByUsr;
	private Date uptdDttm;
	private Set<Tchr> tchrs = new HashSet<Tchr>(0);

	public SchlUsr() {
	}

	public SchlUsr(Schl schl) {
		this.schl = schl;
	}

	public SchlUsr(Schl schl, String idNbr, String crtdByUssr, Date crtdDttm, String uptdByUsr, Date uptdDttm,
			Set<Tchr> tchrs) {
		this.schl = schl;
		this.idNbr = idNbr;
		this.crtdByUssr = crtdByUssr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDttm = uptdDttm;
		this.tchrs = tchrs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SCHL_USR_ID", unique = true, nullable = false)
	public Integer getSchlUsrId() {
		return this.schlUsrId;
	}

	public void setSchlUsrId(Integer schlUsrId) {
		this.schlUsrId = schlUsrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_ID", nullable = false)
	public Schl getSchl() {
		return this.schl;
	}

	public void setSchl(Schl schl) {
		this.schl = schl;
	}

	@Column(name = "ID_NBR", length = 20)
	public String getIdNbr() {
		return this.idNbr;
	}

	public void setIdNbr(String idNbr) {
		this.idNbr = idNbr;
	}

	@Column(name = "CRTD_BY_USSR", length = 15)
	public String getCrtdByUssr() {
		return this.crtdByUssr;
	}

	public void setCrtdByUssr(String crtdByUssr) {
		this.crtdByUssr = crtdByUssr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "UPTD_BY_USR", length = 15)
	public String getUptdByUsr() {
		return this.uptdByUsr;
	}

	public void setUptdByUsr(String uptdByUsr) {
		this.uptdByUsr = uptdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPTD_DTTM", length = 19)
	public Date getUptdDttm() {
		return this.uptdDttm;
	}

	public void setUptdDttm(Date uptdDttm) {
		this.uptdDttm = uptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schlUsr")
	public Set<Tchr> getTchrs() {
		return this.tchrs;
	}

	public void setTchrs(Set<Tchr> tchrs) {
		this.tchrs = tchrs;
	}

}
