package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stdnt generated by hbm2java
 */
@Entity
@Table(name = "stdnt", catalog = "saas_core_db")
public class Stdnt extends AbstractAuditEntity {

	private Long stdntId;
	private DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap;
	private EmgCtct emgCtct;
	private String fstNme;
	private String lstNme;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private String gndr;
	private Set<MrkLst> mrkLsts = new HashSet<MrkLst>(0);
	private Set<Atndnc> atndncs = new HashSet<Atndnc>(0);
	private Set<Ntfn> ntfns = new HashSet<Ntfn>(0);
	private Set<StdntPrntMap> stdntPrntMaps = new HashSet<StdntPrntMap>(0);

	public Stdnt() {
	}

	public Stdnt(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap, EmgCtct emgCtct, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr, String gndr) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
		this.emgCtct = emgCtct;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.gndr = gndr;
	}

	public Stdnt(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap, EmgCtct emgCtct, String fstNme, String lstNme, Date crtdDttm,
			String crtdUsr, Date lstUptdDttm, String lstUptdUsr, String gndr, Set<MrkLst> mrkLsts, Set<Atndnc> atndncs,
			Set<Ntfn> ntfns, Set<StdntPrntMap> stdntPrntMaps) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
		this.emgCtct = emgCtct;
		this.fstNme = fstNme;
		this.lstNme = lstNme;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.gndr = gndr;
		this.mrkLsts = mrkLsts;
		this.atndncs = atndncs;
		this.ntfns = ntfns;
		this.stdntPrntMaps = stdntPrntMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "STDNT_ID", unique = true, nullable = false)
	public Long getStdntId() {
		return this.stdntId;
	}

	public void setStdntId(Long stdntId) {
		this.stdntId = stdntId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVSN_SCHL_GRD_LVL_MAP_ID", nullable = false)
	public DvsnSchlGrdLvlMap getDvsnSchlGrdLvlMap() {
		return this.dvsnSchlGrdLvlMap;
	}

	public void setDvsnSchlGrdLvlMap(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMG_CTCT_ID", nullable = false)
	public EmgCtct getEmgCtct() {
		return this.emgCtct;
	}

	public void setEmgCtct(EmgCtct emgCtct) {
		this.emgCtct = emgCtct;
	}

	@Column(name = "FST_NME", length = 45)
	public String getFstNme() {
		return this.fstNme;
	}

	public void setFstNme(String fstNme) {
		this.fstNme = fstNme;
	}

	@Column(name = "LST_NME", length = 45)
	public String getLstNme() {
		return this.lstNme;
	}

	public void setLstNme(String lstNme) {
		this.lstNme = lstNme;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Column(name = "GNDR", nullable = false, length = 8)
	public String getGndr() {
		return this.gndr;
	}

	public void setGndr(String gndr) {
		this.gndr = gndr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stdnt")
	public Set<MrkLst> getMrkLsts() {
		return this.mrkLsts;
	}

	public void setMrkLsts(Set<MrkLst> mrkLsts) {
		this.mrkLsts = mrkLsts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stdnt")
	public Set<Atndnc> getAtndncs() {
		return this.atndncs;
	}

	public void setAtndncs(Set<Atndnc> atndncs) {
		this.atndncs = atndncs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stdnt")
	public Set<Ntfn> getNtfns() {
		return this.ntfns;
	}

	public void setNtfns(Set<Ntfn> ntfns) {
		this.ntfns = ntfns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stdnt")
	public Set<StdntPrntMap> getStdntPrntMaps() {
		return this.stdntPrntMaps;
	}

	public void setStdntPrntMaps(Set<StdntPrntMap> stdntPrntMaps) {
		this.stdntPrntMaps = stdntPrntMaps;
	}

}
