package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StdntPrntMap generated by hbm2java
 */
@Entity
@Table(name = "stdnt_prnt_map", catalog = "saas_core_db")
public class StdntPrntMap extends AbstractAuditEntity {

	private long stdntPrntMapId;
	private Prnt prnt;
	private Stdnt stdnt;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private int actInd;

	public StdntPrntMap() {
	}

	public StdntPrntMap(long stdntPrntMapId, Prnt prnt, Stdnt stdnt, Date crtdDttm, String crtdUsr, Date lstUptdDttm,
			String lstUptdUsr, int actInd) {
		this.stdntPrntMapId = stdntPrntMapId;
		this.prnt = prnt;
		this.stdnt = stdnt;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.actInd = actInd;
	}

	@Id

	@Column(name = "STDNT_PRNT_MAP_ID", unique = true, nullable = false)
	public long getStdntPrntMapId() {
		return this.stdntPrntMapId;
	}

	public void setStdntPrntMapId(long stdntPrntMapId) {
		this.stdntPrntMapId = stdntPrntMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRNT_ID", nullable = false)
	public Prnt getPrnt() {
		return this.prnt;
	}

	public void setPrnt(Prnt prnt) {
		this.prnt = prnt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STDNT_ID", nullable = false)
	public Stdnt getStdnt() {
		return this.stdnt;
	}

	public void setStdnt(Stdnt stdnt) {
		this.stdnt = stdnt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@Column(name = "ACT_IND", nullable = false)
	public int getActInd() {
		return this.actInd;
	}

	public void setActInd(int actInd) {
		this.actInd = actInd;
	}

}
