package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUsrRole generated by hbm2java
 */
@Entity
@Table(name = "sys_usr_role", catalog = "saas_core_db")
public class SysUsrRole extends AbstractAuditEntity {

	private Integer sysUsrRoleId;
	private String roleNme;
	private String crtdByUsr;
	private Date crtdDttm;
	private String uptdByUsr;
	private Date uptdDttm;
	private Set<SysUsrRoleMap> sysUsrRoleMaps = new HashSet<SysUsrRoleMap>(0);

	public SysUsrRole() {
	}

	public SysUsrRole(String roleNme, String crtdByUsr, Date crtdDttm, String uptdByUsr, Date uptdDttm,
			Set<SysUsrRoleMap> sysUsrRoleMaps) {
		this.roleNme = roleNme;
		this.crtdByUsr = crtdByUsr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDttm = uptdDttm;
		this.sysUsrRoleMaps = sysUsrRoleMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_ROLE_ID", unique = true, nullable = false)
	public Integer getSysUsrRoleId() {
		return this.sysUsrRoleId;
	}

	public void setSysUsrRoleId(Integer sysUsrRoleId) {
		this.sysUsrRoleId = sysUsrRoleId;
	}

	@Column(name = "ROLE_NME", length = 45)
	public String getRoleNme() {
		return this.roleNme;
	}

	public void setRoleNme(String roleNme) {
		this.roleNme = roleNme;
	}

	@Column(name = "CRTD_BY_USR", length = 15)
	public String getCrtdByUsr() {
		return this.crtdByUsr;
	}

	public void setCrtdByUsr(String crtdByUsr) {
		this.crtdByUsr = crtdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "UPTD_BY_USR", length = 15)
	public String getUptdByUsr() {
		return this.uptdByUsr;
	}

	public void setUptdByUsr(String uptdByUsr) {
		this.uptdByUsr = uptdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPTD_DTTM", length = 19)
	public Date getUptdDttm() {
		return this.uptdDttm;
	}

	public void setUptdDttm(Date uptdDttm) {
		this.uptdDttm = uptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsrRole")
	public Set<SysUsrRoleMap> getSysUsrRoleMaps() {
		return this.sysUsrRoleMaps;
	}

	public void setSysUsrRoleMaps(Set<SysUsrRoleMap> sysUsrRoleMaps) {
		this.sysUsrRoleMaps = sysUsrRoleMaps;
	}

}
