package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUsrLogn generated by hbm2java
 */
@Entity
@Table(name = "sys_usr_logn", catalog = "saas_core_db")
public class SysUsrLogn extends AbstractAuditEntity {

	private Integer sysUsrLognId;
	private SysUsr sysUsr;
	private String usrNme;
	private String usrPwd;
	private String usrStat;
	private String crtdByUsr;
	private Date crtdDttm;
	private String uptdByUsr;
	private Date uptdDttm;

	public SysUsrLogn() {
	}

	public SysUsrLogn(SysUsr sysUsr, String usrNme, String usrStat, String crtdByUsr, Date crtdDttm, String uptdByUsr,
			Date uptdDttm) {
		this.sysUsr = sysUsr;
		this.usrNme = usrNme;
		this.usrStat = usrStat;
		this.crtdByUsr = crtdByUsr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDttm = uptdDttm;
	}

	public SysUsrLogn(SysUsr sysUsr, String usrNme, String usrPwd, String usrStat, String crtdByUsr, Date crtdDttm,
			String uptdByUsr, Date uptdDttm) {
		this.sysUsr = sysUsr;
		this.usrNme = usrNme;
		this.usrPwd = usrPwd;
		this.usrStat = usrStat;
		this.crtdByUsr = crtdByUsr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDttm = uptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_LOGN_ID", unique = true, nullable = false)
	public Integer getSysUsrLognId() {
		return this.sysUsrLognId;
	}

	public void setSysUsrLognId(Integer sysUsrLognId) {
		this.sysUsrLognId = sysUsrLognId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SysUsr getSysUsr() {
		return this.sysUsr;
	}

	public void setSysUsr(SysUsr sysUsr) {
		this.sysUsr = sysUsr;
	}

	@Column(name = "USR_NME", nullable = false, length = 45)
	public String getUsrNme() {
		return this.usrNme;
	}

	public void setUsrNme(String usrNme) {
		this.usrNme = usrNme;
	}

	@Column(name = "USR_PWD", length = 45)
	public String getUsrPwd() {
		return this.usrPwd;
	}

	public void setUsrPwd(String usrPwd) {
		this.usrPwd = usrPwd;
	}

	@Column(name = "USR_STAT", nullable = false, length = 10)
	public String getUsrStat() {
		return this.usrStat;
	}

	public void setUsrStat(String usrStat) {
		this.usrStat = usrStat;
	}

	@Column(name = "CRTD_BY_USR", nullable = false, length = 15)
	public String getCrtdByUsr() {
		return this.crtdByUsr;
	}

	public void setCrtdByUsr(String crtdByUsr) {
		this.crtdByUsr = crtdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "UPTD_BY_USR", nullable = false, length = 15)
	public String getUptdByUsr() {
		return this.uptdByUsr;
	}

	public void setUptdByUsr(String uptdByUsr) {
		this.uptdByUsr = uptdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPTD_DTTM", nullable = false, length = 19)
	public Date getUptdDttm() {
		return this.uptdDttm;
	}

	public void setUptdDttm(Date uptdDttm) {
		this.uptdDttm = uptdDttm;
	}

}
