package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUsrProf generated by hbm2java
 */
@Entity
@Table(name = "sys_usr_prof", catalog = "saas_core_db")
public class SysUsrProf extends AbstractAuditEntity {

	private Integer sysUsrProfId;
	private SysUsr sysUsr;
	private String usrEml;
	private String usrPhn;
	private String fstNme;
	private String lstNme;
	private String crtdByUsr;
	private Date crtdDttm;
	private String uptdByUsr;
	private Date uptdDttm;

	public SysUsrProf() {
	}

	public SysUsrProf(SysUsr sysUsr, String usrEml, String usrPhn) {
		this.sysUsr = sysUsr;
		this.usrEml = usrEml;
		this.usrPhn = usrPhn;
	}

	public SysUsrProf(SysUsr sysUsr, String usrEml, String usrPhn, String fstNme, String lstNme, String crtdByUsr,
			Date crtdDttm, String uptdByUsr, Date uptdDttm) {
		this.sysUsr = sysUsr;
		this.usrEml = usrEml;
		this.usrPhn = usrPhn;
		this.fstNme = fstNme;
		this.lstNme = lstNme;
		this.crtdByUsr = crtdByUsr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDttm = uptdDttm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_PROF_ID", unique = true, nullable = false)
	public Integer getSysUsrProfId() {
		return this.sysUsrProfId;
	}

	public void setSysUsrProfId(Integer sysUsrProfId) {
		this.sysUsrProfId = sysUsrProfId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SysUsr getSysUsr() {
		return this.sysUsr;
	}

	public void setSysUsr(SysUsr sysUsr) {
		this.sysUsr = sysUsr;
	}

	@Column(name = "USR_EML", nullable = false, length = 45)
	public String getUsrEml() {
		return this.usrEml;
	}

	public void setUsrEml(String usrEml) {
		this.usrEml = usrEml;
	}

	@Column(name = "USR_PHN", nullable = false, length = 45)
	public String getUsrPhn() {
		return this.usrPhn;
	}

	public void setUsrPhn(String usrPhn) {
		this.usrPhn = usrPhn;
	}

	@Column(name = "FST_NME", length = 45)
	public String getFstNme() {
		return this.fstNme;
	}

	public void setFstNme(String fstNme) {
		this.fstNme = fstNme;
	}

	@Column(name = "LST_NME", length = 45)
	public String getLstNme() {
		return this.lstNme;
	}

	public void setLstNme(String lstNme) {
		this.lstNme = lstNme;
	}

	@Column(name = "CRTD_BY_USR", length = 15)
	public String getCrtdByUsr() {
		return this.crtdByUsr;
	}

	public void setCrtdByUsr(String crtdByUsr) {
		this.crtdByUsr = crtdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "UPTD_BY_USR", length = 15)
	public String getUptdByUsr() {
		return this.uptdByUsr;
	}

	public void setUptdByUsr(String uptdByUsr) {
		this.uptdByUsr = uptdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPTD_DTTM", length = 19)
	public Date getUptdDttm() {
		return this.uptdDttm;
	}

	public void setUptdDttm(Date uptdDttm) {
		this.uptdDttm = uptdDttm;
	}

}
