package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUsr generated by hbm2java
 */
@Entity
@Table(name = "sys_usr", catalog = "saas_core_db")
public class SysUsr extends AbstractAuditEntity {

	private Integer sysUsrId;
	private String idNbr;
	private String crtdByUssr;
	private Date crtdDttm;
	private String uptdByUsr;
	private Date uptdDttm;
	private Set<SysUsrLogn> sysUsrLogns = new HashSet<SysUsrLogn>(0);
	private Set<SysUsrRoleMap> sysUsrRoleMaps = new HashSet<SysUsrRoleMap>(0);
	private Set<SysUsrLognAtmt> sysUsrLognAtmts = new HashSet<SysUsrLognAtmt>(0);
	private Set<SysUsrProf> sysUsrProfs = new HashSet<SysUsrProf>(0);

	public SysUsr() {
	}

	public SysUsr(String idNbr, String crtdByUssr, Date crtdDttm, String uptdByUsr, Date uptdDttm,
			Set<SysUsrLogn> sysUsrLogns, Set<SysUsrRoleMap> sysUsrRoleMaps, Set<SysUsrLognAtmt> sysUsrLognAtmts,
			Set<SysUsrProf> sysUsrProfs) {
		this.idNbr = idNbr;
		this.crtdByUssr = crtdByUssr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDttm = uptdDttm;
		this.sysUsrLogns = sysUsrLogns;
		this.sysUsrRoleMaps = sysUsrRoleMaps;
		this.sysUsrLognAtmts = sysUsrLognAtmts;
		this.sysUsrProfs = sysUsrProfs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_ID", unique = true, nullable = false)
	public Integer getSysUsrId() {
		return this.sysUsrId;
	}

	public void setSysUsrId(Integer sysUsrId) {
		this.sysUsrId = sysUsrId;
	}

	@Column(name = "ID_NBR", length = 20)
	public String getIdNbr() {
		return this.idNbr;
	}

	public void setIdNbr(String idNbr) {
		this.idNbr = idNbr;
	}

	@Column(name = "CRTD_BY_USSR", length = 15)
	public String getCrtdByUssr() {
		return this.crtdByUssr;
	}

	public void setCrtdByUssr(String crtdByUssr) {
		this.crtdByUssr = crtdByUssr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "UPTD_BY_USR", length = 15)
	public String getUptdByUsr() {
		return this.uptdByUsr;
	}

	public void setUptdByUsr(String uptdByUsr) {
		this.uptdByUsr = uptdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPTD_DTTM", length = 19)
	public Date getUptdDttm() {
		return this.uptdDttm;
	}

	public void setUptdDttm(Date uptdDttm) {
		this.uptdDttm = uptdDttm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsr")
	public Set<SysUsrLogn> getSysUsrLogns() {
		return this.sysUsrLogns;
	}

	public void setSysUsrLogns(Set<SysUsrLogn> sysUsrLogns) {
		this.sysUsrLogns = sysUsrLogns;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsr")
	public Set<SysUsrRoleMap> getSysUsrRoleMaps() {
		return this.sysUsrRoleMaps;
	}

	public void setSysUsrRoleMaps(Set<SysUsrRoleMap> sysUsrRoleMaps) {
		this.sysUsrRoleMaps = sysUsrRoleMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsr")
	public Set<SysUsrLognAtmt> getSysUsrLognAtmts() {
		return this.sysUsrLognAtmts;
	}

	public void setSysUsrLognAtmts(Set<SysUsrLognAtmt> sysUsrLognAtmts) {
		this.sysUsrLognAtmts = sysUsrLognAtmts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sysUsr")
	public Set<SysUsrProf> getSysUsrProfs() {
		return this.sysUsrProfs;
	}

	public void setSysUsrProfs(Set<SysUsrProf> sysUsrProfs) {
		this.sysUsrProfs = sysUsrProfs;
	}

}
