package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SysUsrRoleMap generated by hbm2java
 */
@Entity
@Table(name = "sys_usr_role_map", catalog = "saas_core_db")
public class SysUsrRoleMap extends AbstractAuditEntity {

	private Integer sysUsrRoleMapId;
	private SysUsr sysUsr;
	private SysUsrRole sysUsrRole;
	private String roleStatus;
	private String crtdByUsr;
	private Date crtdDttm;
	private String uptdByUsr;
	private Date uptdDtt;
	private String sysUsrRoleNme;

	public SysUsrRoleMap() {
	}

	public SysUsrRoleMap(SysUsr sysUsr, SysUsrRole sysUsrRole) {
		this.sysUsr = sysUsr;
		this.sysUsrRole = sysUsrRole;
	}

	public SysUsrRoleMap(SysUsr sysUsr, SysUsrRole sysUsrRole, String roleStatus, String crtdByUsr, Date crtdDttm,
			String uptdByUsr, Date uptdDtt, String sysUsrRoleNme) {
		this.sysUsr = sysUsr;
		this.sysUsrRole = sysUsrRole;
		this.roleStatus = roleStatus;
		this.crtdByUsr = crtdByUsr;
		this.crtdDttm = crtdDttm;
		this.uptdByUsr = uptdByUsr;
		this.uptdDtt = uptdDtt;
		this.sysUsrRoleNme = sysUsrRoleNme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "SYS_USR_ROLE_MAP_ID", unique = true, nullable = false)
	public Integer getSysUsrRoleMapId() {
		return this.sysUsrRoleMapId;
	}

	public void setSysUsrRoleMapId(Integer sysUsrRoleMapId) {
		this.sysUsrRoleMapId = sysUsrRoleMapId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ID", nullable = false)
	public SysUsr getSysUsr() {
		return this.sysUsr;
	}

	public void setSysUsr(SysUsr sysUsr) {
		this.sysUsr = sysUsr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SYS_USR_ROLE_ID", nullable = false)
	public SysUsrRole getSysUsrRole() {
		return this.sysUsrRole;
	}

	public void setSysUsrRole(SysUsrRole sysUsrRole) {
		this.sysUsrRole = sysUsrRole;
	}

	@Column(name = "ROLE_STATUS", length = 45)
	public String getRoleStatus() {
		return this.roleStatus;
	}

	public void setRoleStatus(String roleStatus) {
		this.roleStatus = roleStatus;
	}

	@Column(name = "CRTD_BY_USR", length = 15)
	public String getCrtdByUsr() {
		return this.crtdByUsr;
	}

	public void setCrtdByUsr(String crtdByUsr) {
		this.crtdByUsr = crtdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "UPTD_BY_USR", length = 15)
	public String getUptdByUsr() {
		return this.uptdByUsr;
	}

	public void setUptdByUsr(String uptdByUsr) {
		this.uptdByUsr = uptdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPTD_DTT", length = 19)
	public Date getUptdDtt() {
		return this.uptdDtt;
	}

	public void setUptdDtt(Date uptdDtt) {
		this.uptdDtt = uptdDtt;
	}

	@Column(name = "SYS_USR_ROLE_NME", length = 45)
	public String getSysUsrRoleNme() {
		return this.sysUsrRoleNme;
	}

	public void setSysUsrRoleNme(String sysUsrRoleNme) {
		this.sysUsrRoleNme = sysUsrRoleNme;
	}

}
