package com.saas.edu.dao.model;
// Generated Jul 31, 2017 10:35:22 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tchr generated by hbm2java
 */
@Entity
@Table(name = "tchr", catalog = "saas_core_db")
public class Tchr extends AbstractAuditEntity {

	private Long tchrId;
	private DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap;
	private SchlUsr schlUsr;
	private String respPri;
	private Date crtdDttm;
	private String crtdUsr;
	private Date lstUptdDttm;
	private String lstUptdUsr;
	private Set<SbjctTchrMap> sbjctTchrMaps = new HashSet<SbjctTchrMap>(0);

	public Tchr() {
	}

	public Tchr(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap, SchlUsr schlUsr, String respPri, Date crtdDttm, String crtdUsr,
			Date lstUptdDttm, String lstUptdUsr) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
		this.schlUsr = schlUsr;
		this.respPri = respPri;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
	}

	public Tchr(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap, SchlUsr schlUsr, String respPri, Date crtdDttm, String crtdUsr,
			Date lstUptdDttm, String lstUptdUsr, Set<SbjctTchrMap> sbjctTchrMaps) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
		this.schlUsr = schlUsr;
		this.respPri = respPri;
		this.crtdDttm = crtdDttm;
		this.crtdUsr = crtdUsr;
		this.lstUptdDttm = lstUptdDttm;
		this.lstUptdUsr = lstUptdUsr;
		this.sbjctTchrMaps = sbjctTchrMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TCHR_ID", unique = true, nullable = false)
	public Long getTchrId() {
		return this.tchrId;
	}

	public void setTchrId(Long tchrId) {
		this.tchrId = tchrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DVSN_SCHL_GRD_LVL_MAP_ID", nullable = false)
	public DvsnSchlGrdLvlMap getDvsnSchlGrdLvlMap() {
		return this.dvsnSchlGrdLvlMap;
	}

	public void setDvsnSchlGrdLvlMap(DvsnSchlGrdLvlMap dvsnSchlGrdLvlMap) {
		this.dvsnSchlGrdLvlMap = dvsnSchlGrdLvlMap;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCHL_USR_ID", nullable = false)
	public SchlUsr getSchlUsr() {
		return this.schlUsr;
	}

	public void setSchlUsr(SchlUsr schlUsr) {
		this.schlUsr = schlUsr;
	}

	@Column(name = "RESP_PRI", nullable = false, length = 45)
	public String getRespPri() {
		return this.respPri;
	}

	public void setRespPri(String respPri) {
		this.respPri = respPri;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CRTD_DTTM", nullable = false, length = 19)
	public Date getCrtdDttm() {
		return this.crtdDttm;
	}

	public void setCrtdDttm(Date crtdDttm) {
		this.crtdDttm = crtdDttm;
	}

	@Column(name = "CRTD_USR", nullable = false, length = 45)
	public String getCrtdUsr() {
		return this.crtdUsr;
	}

	public void setCrtdUsr(String crtdUsr) {
		this.crtdUsr = crtdUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LST_UPTD_DTTM", nullable = false, length = 19)
	public Date getLstUptdDttm() {
		return this.lstUptdDttm;
	}

	public void setLstUptdDttm(Date lstUptdDttm) {
		this.lstUptdDttm = lstUptdDttm;
	}

	@Column(name = "LST_UPTD_USR", nullable = false, length = 45)
	public String getLstUptdUsr() {
		return this.lstUptdUsr;
	}

	public void setLstUptdUsr(String lstUptdUsr) {
		this.lstUptdUsr = lstUptdUsr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tchr")
	public Set<SbjctTchrMap> getSbjctTchrMaps() {
		return this.sbjctTchrMaps;
	}

	public void setSbjctTchrMaps(Set<SbjctTchrMap> sbjctTchrMaps) {
		this.sbjctTchrMaps = sbjctTchrMaps;
	}

}
